"""
Model file created on 2021-08-20 11:07:27.566681 
Created using the automatic src/model_creator.py process.

Original input parameters
Equations:
Aa + Ab = AaAb; KD
AaAb + Ac = AaAbAc; KD
AaAbAc + Ad = AaAbAcAd; KD
AaAbAcAd + Ae = AaAbAcAdAe; KD
AaAbAcAdAe + Af = AaAbAcAdAeAf; KD
AaAbAcAdAeAf + Ag = AaAbAcAdAeAfAg; KD
AaAbAcAdAeAfAg + Ah = AaAbAcAdAeAfAgAh; KD
AaAbAcAdAeAfAgAh + Ai = AaAbAcAdAeAfAgAhAi; KD
AaAbAcAdAeAfAgAhAi + Aj = AaAbAcAdAeAfAgAhAiAj; KD
AaAbAcAdAeAfAgAhAiAj + Ak = AaAbAcAdAeAfAgAhAiAjAk; KD
AaAbAcAdAeAfAgAhAiAjAk + Al = AaAbAcAdAeAfAgAhAiAjAkAl; KD
AaAbAcAdAeAfAgAhAiAjAkAl + Am = AaAbAcAdAeAfAgAhAiAjAkAlAm; KD
AaAbAcAdAeAfAgAhAiAjAkAlAm + An = AaAbAcAdAeAfAgAhAiAjAkAlAmAn; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAn + Ao = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAo; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAo + Ap = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoAp; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoAp + Aq = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAq; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAq + Ar = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqAr; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqAr + As = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAs; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAs + At = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAt; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAt + Au = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAu; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAu + Av = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAv; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAv + Aw = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAw; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAw + Ax = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAx; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAx + Ay = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAy; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAy + Az = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz + Ba = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBa; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBa + Bb = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBb; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBb + Bc = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBc; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBc + Bd = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBd; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBd + Be = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBe; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBe + Bf = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBf; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBf + Bg = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBg; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBg + Bh = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBh; KD
AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBh + Bi = AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBhBi; KD

Labeled specie: Aa
data_mode: anisotropy
"""

import numpy as np

# All variables for this model
variables = ['AaAbAc', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAt', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBc', 'At', 'As', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAu', 'AaAbAcAdAeAfAg', 'Av', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBhBi', 'Ak', 'AaAbAcAdAeAfAgAhAiAjAkAlAm', 'AaAbAcAdAeAfAgAhAiAj', 'Az', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAw', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz', 'AaAbAcAdAeAfAgAh', 'AaAbAcAdAeAfAgAhAiAjAkAl', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBg', 'Bh', 'Al', 'AaAbAcAdAeAf', 'Ae', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAo', 'Ac', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBf', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAx', 'Ai', 'An', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqAr', 'Bf', 'Au', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAs', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoAp', 'Bc', 'Bd', 'AaAb', 'Af', 'AaAbAcAdAe', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAq', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBa', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBb', 'Aj', 'Aa', 'Ap', 'AaAbAcAd', 'Aq', 'Ba', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBd', 'Bg', 'Ax', 'Am', 'Ad', 'Ay', 'Be', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAn', 'Ab', 'AaAbAcAdAeAfAgAhAiAjAk', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAv', 'AaAbAcAdAeAfAgAhAi', 'Bb', 'Ag', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBh', 'KD', 'Ar', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBe', 'Ah', 'Ao', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAy', 'Aw', 'Bi', 'At_tot', 'As_tot', 'Av_tot', 'Ak_tot', 'Az_tot', 'Bh_tot', 'Al_tot', 'Ae_tot', 'Ac_tot', 'Ai_tot', 'An_tot', 'Bf_tot', 'Au_tot', 'Bc_tot', 'Bd_tot', 'Af_tot', 'Aj_tot', 'Aa_tot', 'Ap_tot', 'Aq_tot', 'Ba_tot', 'Bg_tot', 'Ax_tot', 'Am_tot', 'Ad_tot', 'Ay_tot', 'Be_tot', 'Ab_tot', 'Bb_tot', 'Ag_tot', 'Ar_tot', 'Ah_tot', 'Ao_tot', 'Aw_tot', 'Bi_tot']
# The species for which the concentrations need to be determined
# in order to solve the system. Will have the same order as system_equations.
independent_species = ['At', 'As', 'Av', 'Ak', 'Az', 'Bh', 'Al', 'Ae', 'Ac', 'Ai', 'An', 'Bf', 'Au', 'Bc', 'Bd', 'Af', 'Aj', 'Aa', 'Ap', 'Aq', 'Ba', 'Bg', 'Ax', 'Am', 'Ad', 'Ay', 'Be', 'Ab', 'Bb', 'Ag', 'Ar', 'Ah', 'Ao', 'Aw', 'Bi']
# Species who's concentration can be determined from others
dependent_species = ['AaAb', 'AaAbAc', 'AaAbAcAd', 'AaAbAcAdAe', 'AaAbAcAdAeAf', 'AaAbAcAdAeAfAg', 'AaAbAcAdAeAfAgAh', 'AaAbAcAdAeAfAgAhAi', 'AaAbAcAdAeAfAgAhAiAj', 'AaAbAcAdAeAfAgAhAiAjAk', 'AaAbAcAdAeAfAgAhAiAjAkAl', 'AaAbAcAdAeAfAgAhAiAjAkAlAm', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAn', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAo', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoAp', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAq', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqAr', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAs', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAt', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAu', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAv', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAw', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAx', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAy', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBa', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBb', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBc', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBd', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBe', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBf', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBg', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBh', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBhBi']
# The constant terms in the model
constants = ['KD']
# Which components are labeled / detected in the experiment
labeled_components = ['AaAbAc', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAt', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBc', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAu', 'AaAbAcAdAeAfAg', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBhBi', 'AaAbAcAdAeAfAgAhAiAjAkAlAm', 'AaAbAcAdAeAfAgAhAiAj', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAw', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz', 'AaAbAcAdAeAfAgAh', 'AaAbAcAdAeAfAgAhAiAjAkAl', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBg', 'AaAbAcAdAeAf', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAo', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBf', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAx', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqAr', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAs', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoAp', 'AaAb', 'AaAbAcAdAe', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAq', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBa', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBb', 'Aa', 'AaAbAcAd', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBd', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAn', 'AaAbAcAdAeAfAgAhAiAjAk', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAv', 'AaAbAcAdAeAfAgAhAi', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBh', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBe', 'AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAy'] 

def system_equations(concentrations, state):
    """
    The equilibrium equations for this system. If an input result in the zero
    vector, that input is a solution to the system.
    """
    # Potential solution of the system
    At = concentrations[0]
    As = concentrations[1]
    Av = concentrations[2]
    Ak = concentrations[3]
    Az = concentrations[4]
    Bh = concentrations[5]
    Al = concentrations[6]
    Ae = concentrations[7]
    Ac = concentrations[8]
    Ai = concentrations[9]
    An = concentrations[10]
    Bf = concentrations[11]
    Au = concentrations[12]
    Bc = concentrations[13]
    Bd = concentrations[14]
    Af = concentrations[15]
    Aj = concentrations[16]
    Aa = concentrations[17]
    Ap = concentrations[18]
    Aq = concentrations[19]
    Ba = concentrations[20]
    Bg = concentrations[21]
    Ax = concentrations[22]
    Am = concentrations[23]
    Ad = concentrations[24]
    Ay = concentrations[25]
    Be = concentrations[26]
    Ab = concentrations[27]
    Bb = concentrations[28]
    Ag = concentrations[29]
    Ar = concentrations[30]
    Ah = concentrations[31]
    Ao = concentrations[32]
    Aw = concentrations[33]
    Bi = concentrations[34]

    # Readability
    Aa_tot = state.Aa_tot
    Ab_tot = state.Ab_tot
    Ac_tot = state.Ac_tot
    Ad_tot = state.Ad_tot
    Ae_tot = state.Ae_tot
    Af_tot = state.Af_tot
    Ag_tot = state.Ag_tot
    Ah_tot = state.Ah_tot
    Ai_tot = state.Ai_tot
    Aj_tot = state.Aj_tot
    Ak_tot = state.Ak_tot
    Al_tot = state.Al_tot
    Am_tot = state.Am_tot
    An_tot = state.An_tot
    Ao_tot = state.Ao_tot
    Ap_tot = state.Ap_tot
    Aq_tot = state.Aq_tot
    Ar_tot = state.Ar_tot
    As_tot = state.As_tot
    At_tot = state.At_tot
    Au_tot = state.Au_tot
    Av_tot = state.Av_tot
    Aw_tot = state.Aw_tot
    Ax_tot = state.Ax_tot
    Ay_tot = state.Ay_tot
    Az_tot = state.Az_tot
    Ba_tot = state.Ba_tot
    Bb_tot = state.Bb_tot
    Bc_tot = state.Bc_tot
    Bd_tot = state.Bd_tot
    Be_tot = state.Be_tot
    Bf_tot = state.Bf_tot
    Bg_tot = state.Bg_tot
    Bh_tot = state.Bh_tot
    Bi_tot = state.Bi_tot
    KD = state.KD

    result = np.zeros(35)
    result[0] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + At - At_tot) / At_tot
    result[1] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + As - As_tot) / As_tot
    result[2] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Av - Av_tot) / Av_tot
    result[3] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Ak - Ak_tot) / Ak_tot
    result[4] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Az - Az_tot) / Az_tot
    result[5] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Bh - Bh_tot) / Bh_tot
    result[6] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Al - Al_tot) / Al_tot
    result[7] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah/KD**7 + Aa*Ab*Ac*Ad*Ae*Af*Ag/KD**6 + Aa*Ab*Ac*Ad*Ae*Af/KD**5 + Aa*Ab*Ac*Ad*Ae/KD**4 + Ae - Ae_tot) / Ae_tot
    result[8] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah/KD**7 + Aa*Ab*Ac*Ad*Ae*Af*Ag/KD**6 + Aa*Ab*Ac*Ad*Ae*Af/KD**5 + Aa*Ab*Ac*Ad*Ae/KD**4 + Aa*Ab*Ac*Ad/KD**3 + Aa*Ab*Ac/KD**2 + Ac - Ac_tot) / Ac_tot
    result[9] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8 + Ai - Ai_tot) / Ai_tot
    result[10] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + An - An_tot) / An_tot
    result[11] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Bf - Bf_tot) / Bf_tot
    result[12] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Au - Au_tot) / Au_tot
    result[13] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Bc - Bc_tot) / Bc_tot
    result[14] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Bd - Bd_tot) / Bd_tot
    result[15] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah/KD**7 + Aa*Ab*Ac*Ad*Ae*Af*Ag/KD**6 + Aa*Ab*Ac*Ad*Ae*Af/KD**5 + Af - Af_tot) / Af_tot
    result[16] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aj - Aj_tot) / Aj_tot
    result[17] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah/KD**7 + Aa*Ab*Ac*Ad*Ae*Af*Ag/KD**6 + Aa*Ab*Ac*Ad*Ae*Af/KD**5 + Aa*Ab*Ac*Ad*Ae/KD**4 + Aa*Ab*Ac*Ad/KD**3 + Aa*Ab*Ac/KD**2 + Aa*Ab/KD + Aa - Aa_tot) / Aa_tot
    result[18] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Ap - Ap_tot) / Ap_tot
    result[19] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aq - Aq_tot) / Aq_tot
    result[20] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Ba - Ba_tot) / Ba_tot
    result[21] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Bg - Bg_tot) / Bg_tot
    result[22] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Ax - Ax_tot) / Ax_tot
    result[23] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Am - Am_tot) / Am_tot
    result[24] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah/KD**7 + Aa*Ab*Ac*Ad*Ae*Af*Ag/KD**6 + Aa*Ab*Ac*Ad*Ae*Af/KD**5 + Aa*Ab*Ac*Ad*Ae/KD**4 + Aa*Ab*Ac*Ad/KD**3 + Ad - Ad_tot) / Ad_tot
    result[25] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Ay - Ay_tot) / Ay_tot
    result[26] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Be - Be_tot) / Be_tot
    result[27] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah/KD**7 + Aa*Ab*Ac*Ad*Ae*Af*Ag/KD**6 + Aa*Ab*Ac*Ad*Ae*Af/KD**5 + Aa*Ab*Ac*Ad*Ae/KD**4 + Aa*Ab*Ac*Ad/KD**3 + Aa*Ab*Ac/KD**2 + Aa*Ab/KD + Ab - Ab_tot) / Ab_tot
    result[28] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Bb - Bb_tot) / Bb_tot
    result[29] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah/KD**7 + Aa*Ab*Ac*Ad*Ae*Af*Ag/KD**6 + Ag - Ag_tot) / Ag_tot
    result[30] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Ar - Ar_tot) / Ar_tot
    result[31] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah/KD**7 + Ah - Ah_tot) / Ah_tot
    result[32] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14 + Ao - Ao_tot) / Ao_tot
    result[33] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23 + Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22 + Aw - Aw_tot) / Aw_tot
    result[34] = (Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34 + Bi - Bi_tot) / Bi_tot
    return result 


def update_state(solution, state):
    """
    Given a solution to the system_equations, update the state object to 
    reflect this solution.
    """
    # Independent variables
    state.At = solution[0]
    state.As = solution[1]
    state.Av = solution[2]
    state.Ak = solution[3]
    state.Az = solution[4]
    state.Bh = solution[5]
    state.Al = solution[6]
    state.Ae = solution[7]
    state.Ac = solution[8]
    state.Ai = solution[9]
    state.An = solution[10]
    state.Bf = solution[11]
    state.Au = solution[12]
    state.Bc = solution[13]
    state.Bd = solution[14]
    state.Af = solution[15]
    state.Aj = solution[16]
    state.Aa = solution[17]
    state.Ap = solution[18]
    state.Aq = solution[19]
    state.Ba = solution[20]
    state.Bg = solution[21]
    state.Ax = solution[22]
    state.Am = solution[23]
    state.Ad = solution[24]
    state.Ay = solution[25]
    state.Be = solution[26]
    state.Ab = solution[27]
    state.Bb = solution[28]
    state.Ag = solution[29]
    state.Ar = solution[30]
    state.Ah = solution[31]
    state.Ao = solution[32]
    state.Aw = solution[33]
    state.Bi = solution[34]

    # Readability 
    Aa = state.Aa
    Ab = state.Ab
    Ac = state.Ac
    Ad = state.Ad
    Ae = state.Ae
    Af = state.Af
    Ag = state.Ag
    Ah = state.Ah
    Ai = state.Ai
    Aj = state.Aj
    Ak = state.Ak
    Al = state.Al
    Am = state.Am
    An = state.An
    Ao = state.Ao
    Ap = state.Ap
    Aq = state.Aq
    Ar = state.Ar
    As = state.As
    At = state.At
    Au = state.Au
    Av = state.Av
    Aw = state.Aw
    Ax = state.Ax
    Ay = state.Ay
    Az = state.Az
    Ba = state.Ba
    Bb = state.Bb
    Bc = state.Bc
    Bd = state.Bd
    Be = state.Be
    Bf = state.Bf
    Bg = state.Bg
    Bh = state.Bh
    Bi = state.Bi
    KD = state.KD

    # Dependent variables
    state.AaAb = Aa*Ab/KD
    state.AaAbAc = Aa*Ab*Ac/KD**2
    state.AaAbAcAd = Aa*Ab*Ac*Ad/KD**3
    state.AaAbAcAdAe = Aa*Ab*Ac*Ad*Ae/KD**4
    state.AaAbAcAdAeAf = Aa*Ab*Ac*Ad*Ae*Af/KD**5
    state.AaAbAcAdAeAfAg = Aa*Ab*Ac*Ad*Ae*Af*Ag/KD**6
    state.AaAbAcAdAeAfAgAh = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah/KD**7
    state.AaAbAcAdAeAfAgAhAi = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai/KD**8
    state.AaAbAcAdAeAfAgAhAiAj = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj/KD**9
    state.AaAbAcAdAeAfAgAhAiAjAk = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak/KD**10
    state.AaAbAcAdAeAfAgAhAiAjAkAl = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al/KD**11
    state.AaAbAcAdAeAfAgAhAiAjAkAlAm = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am/KD**12
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAn = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An/KD**13
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAo = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao/KD**14
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoAp = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap/KD**15
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAq = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq/KD**16
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqAr = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar/KD**17
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAs = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As/KD**18
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAt = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At/KD**19
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAu = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au/KD**20
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAv = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av/KD**21
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAw = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw/KD**22
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAx = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax/KD**23
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAy = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay/KD**24
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az/KD**25
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBa = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba/KD**26
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBb = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb/KD**27
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBc = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc/KD**28
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBd = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd/KD**29
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBe = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be/KD**30
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBf = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf/KD**31
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBg = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg/KD**32
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBh = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh/KD**33
    state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBhBi = Aa*Ab*Ac*Ad*Ae*Af*Ag*Ah*Ai*Aj*Ak*Al*Am*An*Ao*Ap*Aq*Ar*As*At*Au*Av*Aw*Ax*Ay*Az*Ba*Bb*Bc*Bd*Be*Bf*Bg*Bh*Bi/KD**34


def data_function(state):
    """
    Function to map state object to experimental data values.
    """
    # Readability
    Aa = state.Aa
    AaAb = state.AaAb
    AaAbAc = state.AaAbAc
    AaAbAcAd = state.AaAbAcAd
    AaAbAcAdAe = state.AaAbAcAdAe
    AaAbAcAdAeAf = state.AaAbAcAdAeAf
    AaAbAcAdAeAfAg = state.AaAbAcAdAeAfAg
    AaAbAcAdAeAfAgAh = state.AaAbAcAdAeAfAgAh
    AaAbAcAdAeAfAgAhAi = state.AaAbAcAdAeAfAgAhAi
    AaAbAcAdAeAfAgAhAiAj = state.AaAbAcAdAeAfAgAhAiAj
    AaAbAcAdAeAfAgAhAiAjAk = state.AaAbAcAdAeAfAgAhAiAjAk
    AaAbAcAdAeAfAgAhAiAjAkAl = state.AaAbAcAdAeAfAgAhAiAjAkAl
    AaAbAcAdAeAfAgAhAiAjAkAlAm = state.AaAbAcAdAeAfAgAhAiAjAkAlAm
    AaAbAcAdAeAfAgAhAiAjAkAlAmAn = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAn
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAo = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAo
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoAp = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoAp
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAq = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAq
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqAr = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqAr
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAs = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAs
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAt = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAt
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAu = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAu
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAv = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAv
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAw = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAw
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAx = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAx
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAy = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAy
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBa = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBa
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBb = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBb
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBc = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBc
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBd = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBd
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBe = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBe
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBf = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBf
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBg = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBg
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBh = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBh
    AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBhBi = state.AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBhBi
    Aa_tot = state.Aa_tot
    data_max = state.data_max
    data_min = state.data_min

    return Aa*data_min/Aa_tot + data_max*(AaAb + AaAbAc + AaAbAcAd + AaAbAcAdAe + AaAbAcAdAeAf + AaAbAcAdAeAfAg + AaAbAcAdAeAfAgAh + AaAbAcAdAeAfAgAhAi + AaAbAcAdAeAfAgAhAiAj + AaAbAcAdAeAfAgAhAiAjAk + AaAbAcAdAeAfAgAhAiAjAkAl + AaAbAcAdAeAfAgAhAiAjAkAlAm + AaAbAcAdAeAfAgAhAiAjAkAlAmAn + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAo + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoAp + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAq + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqAr + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAs + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAt + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAu + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAv + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAw + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAx + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAy + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAz + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBa + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBb + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBc + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBd + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBe + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBf + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBg + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBh + AaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzBaBbBcBdBeBfBgBhBi)/Aa_tot


