"""
Model file created on 2021-08-20 14:18:44.706292 
Created using the automatic src/model_creator.py process.

Original input parameters
Equations:
A + B = AB; Kd
A + C = AC; Kd
A + D = AD; Kd
A + E = AE; Kd
A + F = AF; Kd
A + G = AG; Kd
A + H = AH; Kd
A + I = AI; Kd
B + C = BC; Kd
B + D = BD; Kd
B + E = BE; Kd
B + F = BF; Kd
B + G = BG; Kd
B + H = BH; Kd
B + I = BI; Kd
C + D = CD; Kd
C + E = CE; Kd
C + F = CF; Kd
C + G = CG; Kd
C + H = CH; Kd
C + I = CI; Kd
D + E = DE; Kd
D + F = DF; Kd
D + G = DG; Kd
D + H = DH; Kd
D + I = DI; Kd
E + F = EF; Kd
E + G = EG; Kd
E + H = EH; Kd
E + I = EI; Kd
F + G = FG; Kd
F + H = FH; Kd
F + I = FI; Kd
G + H = GH; Kd
G + I = GI; Kd
H + I = HI; Kd
AB + C = ABC; Kd
AB + D = ABD; Kd
AB + E = ABE; Kd
AB + F = ABF; Kd
AB + G = ABG; Kd
AB + H = ABH; Kd
AB + I = ABI; Kd
AC + D = ACD; Kd
AC + E = ACE; Kd
AC + F = ACF; Kd
AC + G = ACG; Kd
AC + H = ACH; Kd
AC + I = ACI; Kd
AD + E = ADE; Kd
AD + F = ADF; Kd
AD + G = ADG; Kd
AD + H = ADH; Kd
AD + I = ADI; Kd
AE + F = AEF; Kd
AE + G = AEG; Kd
AE + H = AEH; Kd
AE + I = AEI; Kd
AF + G = AFG; Kd
AF + H = AFH; Kd
AF + I = AFI; Kd
AG + H = AGH; Kd
AG + I = AGI; Kd
AH + I = AHI; Kd
BC + D = BCD; Kd
BC + E = BCE; Kd
BC + F = BCF; Kd
BC + G = BCG; Kd
BC + H = BCH; Kd
BC + I = BCI; Kd
BD + E = BDE; Kd
BD + F = BDF; Kd
BD + G = BDG; Kd
BD + H = BDH; Kd
BD + I = BDI; Kd
BE + F = BEF; Kd
BE + G = BEG; Kd
BE + H = BEH; Kd
BE + I = BEI; Kd
BF + G = BFG; Kd
BF + H = BFH; Kd
BF + I = BFI; Kd
BG + H = BGH; Kd
BG + I = BGI; Kd
BH + I = BHI; Kd
CD + E = CDE; Kd
CD + F = CDF; Kd
CD + G = CDG; Kd
CD + H = CDH; Kd
CD + I = CDI; Kd
CE + F = CEF; Kd
CE + G = CEG; Kd
CE + H = CEH; Kd
CE + I = CEI; Kd
CF + G = CFG; Kd
CF + H = CFH; Kd
CF + I = CFI; Kd
CG + H = CGH; Kd
CG + I = CGI; Kd
CH + I = CHI; Kd
DE + F = DEF; Kd
DE + G = DEG; Kd
DE + H = DEH; Kd
DE + I = DEI; Kd
DF + G = DFG; Kd
DF + H = DFH; Kd
DF + I = DFI; Kd
DG + H = DGH; Kd
DG + I = DGI; Kd
DH + I = DHI; Kd
EF + G = EFG; Kd
EF + H = EFH; Kd
EF + I = EFI; Kd
EG + H = EGH; Kd
EG + I = EGI; Kd
EH + I = EHI; Kd
FG + H = FGH; Kd
FG + I = FGI; Kd
FH + I = FHI; Kd
GH + I = GHI; Kd
ABC + D = ABCD; Kd
ABC + E = ABCE; Kd
ABC + F = ABCF; Kd
ABC + G = ABCG; Kd
ABC + H = ABCH; Kd
ABC + I = ABCI; Kd
ABD + E = ABDE; Kd
ABD + F = ABDF; Kd
ABD + G = ABDG; Kd
ABD + H = ABDH; Kd
ABD + I = ABDI; Kd
ABE + F = ABEF; Kd
ABE + G = ABEG; Kd
ABE + H = ABEH; Kd
ABE + I = ABEI; Kd
ABF + G = ABFG; Kd
ABF + H = ABFH; Kd
ABF + I = ABFI; Kd
ABG + H = ABGH; Kd
ABG + I = ABGI; Kd
ABH + I = ABHI; Kd
ACD + E = ACDE; Kd
ACD + F = ACDF; Kd
ACD + G = ACDG; Kd
ACD + H = ACDH; Kd
ACD + I = ACDI; Kd
ACE + F = ACEF; Kd
ACE + G = ACEG; Kd
ACE + H = ACEH; Kd
ACE + I = ACEI; Kd
ACF + G = ACFG; Kd
ACF + H = ACFH; Kd
ACF + I = ACFI; Kd
ACG + H = ACGH; Kd
ACG + I = ACGI; Kd
ACH + I = ACHI; Kd
ADE + F = ADEF; Kd
ADE + G = ADEG; Kd
ADE + H = ADEH; Kd
ADE + I = ADEI; Kd
ADF + G = ADFG; Kd
ADF + H = ADFH; Kd
ADF + I = ADFI; Kd
ADG + H = ADGH; Kd
ADG + I = ADGI; Kd
ADH + I = ADHI; Kd
AEF + G = AEFG; Kd
AEF + H = AEFH; Kd
AEF + I = AEFI; Kd
AEG + H = AEGH; Kd
AEG + I = AEGI; Kd
AEH + I = AEHI; Kd
AFG + H = AFGH; Kd
AFG + I = AFGI; Kd
AFH + I = AFHI; Kd
AGH + I = AGHI; Kd
BCD + E = BCDE; Kd
BCD + F = BCDF; Kd
BCD + G = BCDG; Kd
BCD + H = BCDH; Kd
BCD + I = BCDI; Kd
BCE + F = BCEF; Kd
BCE + G = BCEG; Kd
BCE + H = BCEH; Kd
BCE + I = BCEI; Kd
BCF + G = BCFG; Kd
BCF + H = BCFH; Kd
BCF + I = BCFI; Kd
BCG + H = BCGH; Kd
BCG + I = BCGI; Kd
BCH + I = BCHI; Kd
BDE + F = BDEF; Kd
BDE + G = BDEG; Kd
BDE + H = BDEH; Kd
BDE + I = BDEI; Kd
BDF + G = BDFG; Kd
BDF + H = BDFH; Kd
BDF + I = BDFI; Kd
BDG + H = BDGH; Kd
BDG + I = BDGI; Kd
BDH + I = BDHI; Kd
BEF + G = BEFG; Kd
BEF + H = BEFH; Kd
BEF + I = BEFI; Kd
BEG + H = BEGH; Kd
BEG + I = BEGI; Kd
BEH + I = BEHI; Kd
BFG + H = BFGH; Kd
BFG + I = BFGI; Kd
BFH + I = BFHI; Kd
BGH + I = BGHI; Kd
CDE + F = CDEF; Kd
CDE + G = CDEG; Kd
CDE + H = CDEH; Kd
CDE + I = CDEI; Kd
CDF + G = CDFG; Kd
CDF + H = CDFH; Kd
CDF + I = CDFI; Kd
CDG + H = CDGH; Kd
CDG + I = CDGI; Kd
CDH + I = CDHI; Kd
CEF + G = CEFG; Kd
CEF + H = CEFH; Kd
CEF + I = CEFI; Kd
CEG + H = CEGH; Kd
CEG + I = CEGI; Kd
CEH + I = CEHI; Kd
CFG + H = CFGH; Kd
CFG + I = CFGI; Kd
CFH + I = CFHI; Kd
CGH + I = CGHI; Kd
DEF + G = DEFG; Kd
DEF + H = DEFH; Kd
DEF + I = DEFI; Kd
DEG + H = DEGH; Kd
DEG + I = DEGI; Kd
DEH + I = DEHI; Kd
DFG + H = DFGH; Kd
DFG + I = DFGI; Kd
DFH + I = DFHI; Kd
DGH + I = DGHI; Kd
EFG + H = EFGH; Kd
EFG + I = EFGI; Kd
EFH + I = EFHI; Kd
EGH + I = EGHI; Kd
FGH + I = FGHI; Kd

Labeled specie: A
data_mode: anisotropy
"""

import numpy as np

# All variables for this model
variables = ['CDH', 'ACH', 'ADGH', 'EFH', 'BEHI', 'DEFI', 'DEFG', 'DFHI', 'CDEF', 'ACDI', 'CDF', 'ADF', 'BC', 'ABEI', 'ABGI', 'ADEF', 'F', 'AEHI', 'AFHI', 'DFGH', 'ACEF', 'GI', 'ADFH', 'ABCE', 'DFGI', 'CDGH', 'BGHI', 'ABCD', 'BHI', 'CFGI', 'ACEG', 'AFI', 'CEH', 'GH', 'ADFG', 'ABCG', 'DH', 'CFI', 'CDEG', 'ACE', 'EGHI', 'CDG', 'CDFG', 'BCH', 'BDFI', 'DI', 'BDEH', 'BCFG', 'CF', 'EFHI', 'BDE', 'ACD', 'CEGH', 'BCI', 'AEFH', 'BEFG', 'ACFG', 'CEFH', 'AEFG', 'BDEG', 'BDGH', 'CEFG', 'BDG', 'FG', 'BDGI', 'BF', 'CFHI', 'B', 'AEFI', 'BEF', 'BEGI', 'AC', 'AEH', 'FI', 'ABEH', 'BCEH', 'ABGH', 'ADEH', 'ADHI', 'BDFH', 'BCEG', 'ACFI', 'EI', 'ABI', 'BEH', 'CHI', 'CD', 'AG', 'ACDE', 'DGH', 'I', 'BEG', 'CDFI', 'BCF', 'CGI', 'ABFG', 'ACEH', 'DFG', 'CFH', 'BCHI', 'BDHI', 'BEI', 'BDF', 'ABDH', 'DEFH', 'BCE', 'AFGH', 'BFG', 'FGHI', 'EFG', 'CFG', 'EFI', 'EFGI', 'EF', 'CEGI', 'CDGI', 'BGH', 'BCD', 'BCDG', 'AF', 'BEGH', 'ABG', 'CEG', 'BEFH', 'A', 'ACG', 'ADG', 'ACDH', 'DE', 'E', 'AEF', 'D', 'EGH', 'CEF', 'ADEI', 'DF', 'ACFH', 'CEHI', 'ABC', 'BH', 'BCDE', 'ABDG', 'ABH', 'ACHI', 'BCFI', 'HI', 'AFG', 'BCG', 'BFGH', 'DHI', 'CDHI', 'GHI', 'ADFI', 'ABD', 'BCFH', 'BCGH', 'H', 'BCDI', 'BE', 'BI', 'Kd', 'AGHI', 'ACGH', 'AE', 'BFI', 'DEGH', 'CG', 'AEI', 'EHI', 'ACDG', 'BDEF', 'ABCI', 'AGI', 'BFHI', 'BDH', 'DGI', 'ABEF', 'AEGH', 'EFGH', 'BDFG', 'CE', 'CDEI', 'CH', 'BDI', 'BG', 'FHI', 'ACEI', 'ABDI', 'BCGI', 'AHI', 'CEFI', 'DG', 'FH', 'ABFI', 'CDEH', 'AFH', 'ADH', 'DEHI', 'DEH', 'AD', 'AFGI', 'EGI', 'CGHI', 'DEGI', 'AB', 'ADE', 'ABDE', 'BCDH', 'ACI', 'ABCF', 'ABF', 'AEGI', 'ABEG', 'ADI', 'BCEI', 'G', 'BDEI', 'ADGI', 'BFGI', 'DFI', 'BGI', 'DEG', 'ACDF', 'DGHI', 'CGH', 'DFH', 'EG', 'ABFH', 'ABHI', 'DEI', 'ABE', 'EH', 'ADEG', 'CDFH', 'BCEF', 'ACF', 'AH', 'AEG', 'FGH', 'BEFI', 'CFGH', 'FGI', 'AGH', 'BCDF', 'ACGI', 'ABCH', 'AI', 'DEF', 'ABDF', 'CDE', 'CDI', 'BFH', 'CI', 'CEI', 'C', 'BD', 'B_tot', 'F_tot', 'G_tot', 'A_tot', 'E_tot', 'I_tot', 'D_tot', 'H_tot', 'C_tot']
# The species for which the concentrations need to be determined
# in order to solve the system. Will have the same order as system_equations.
independent_species = ['B', 'F', 'G', 'A', 'E', 'I', 'D', 'H', 'C']
# Species who's concentration can be determined from others
dependent_species = ['AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'CD', 'CE', 'CF', 'CG', 'CH', 'CI', 'DE', 'DF', 'DG', 'DH', 'DI', 'EF', 'EG', 'EH', 'EI', 'FG', 'FH', 'FI', 'GH', 'GI', 'HI', 'ABC', 'ABD', 'ABE', 'ABF', 'ABG', 'ABH', 'ABI', 'ACD', 'ACE', 'ACF', 'ACG', 'ACH', 'ACI', 'ADE', 'ADF', 'ADG', 'ADH', 'ADI', 'AEF', 'AEG', 'AEH', 'AEI', 'AFG', 'AFH', 'AFI', 'AGH', 'AGI', 'AHI', 'BCD', 'BCE', 'BCF', 'BCG', 'BCH', 'BCI', 'BDE', 'BDF', 'BDG', 'BDH', 'BDI', 'BEF', 'BEG', 'BEH', 'BEI', 'BFG', 'BFH', 'BFI', 'BGH', 'BGI', 'BHI', 'CDE', 'CDF', 'CDG', 'CDH', 'CDI', 'CEF', 'CEG', 'CEH', 'CEI', 'CFG', 'CFH', 'CFI', 'CGH', 'CGI', 'CHI', 'DEF', 'DEG', 'DEH', 'DEI', 'DFG', 'DFH', 'DFI', 'DGH', 'DGI', 'DHI', 'EFG', 'EFH', 'EFI', 'EGH', 'EGI', 'EHI', 'FGH', 'FGI', 'FHI', 'GHI', 'ABCD', 'ABCE', 'ABCF', 'ABCG', 'ABCH', 'ABCI', 'ABDE', 'ABDF', 'ABDG', 'ABDH', 'ABDI', 'ABEF', 'ABEG', 'ABEH', 'ABEI', 'ABFG', 'ABFH', 'ABFI', 'ABGH', 'ABGI', 'ABHI', 'ACDE', 'ACDF', 'ACDG', 'ACDH', 'ACDI', 'ACEF', 'ACEG', 'ACEH', 'ACEI', 'ACFG', 'ACFH', 'ACFI', 'ACGH', 'ACGI', 'ACHI', 'ADEF', 'ADEG', 'ADEH', 'ADEI', 'ADFG', 'ADFH', 'ADFI', 'ADGH', 'ADGI', 'ADHI', 'AEFG', 'AEFH', 'AEFI', 'AEGH', 'AEGI', 'AEHI', 'AFGH', 'AFGI', 'AFHI', 'AGHI', 'BCDE', 'BCDF', 'BCDG', 'BCDH', 'BCDI', 'BCEF', 'BCEG', 'BCEH', 'BCEI', 'BCFG', 'BCFH', 'BCFI', 'BCGH', 'BCGI', 'BCHI', 'BDEF', 'BDEG', 'BDEH', 'BDEI', 'BDFG', 'BDFH', 'BDFI', 'BDGH', 'BDGI', 'BDHI', 'BEFG', 'BEFH', 'BEFI', 'BEGH', 'BEGI', 'BEHI', 'BFGH', 'BFGI', 'BFHI', 'BGHI', 'CDEF', 'CDEG', 'CDEH', 'CDEI', 'CDFG', 'CDFH', 'CDFI', 'CDGH', 'CDGI', 'CDHI', 'CEFG', 'CEFH', 'CEFI', 'CEGH', 'CEGI', 'CEHI', 'CFGH', 'CFGI', 'CFHI', 'CGHI', 'DEFG', 'DEFH', 'DEFI', 'DEGH', 'DEGI', 'DEHI', 'DFGH', 'DFGI', 'DFHI', 'DGHI', 'EFGH', 'EFGI', 'EFHI', 'EGHI', 'FGHI']
# The constant terms in the model
constants = ['Kd']
# Which components are labeled / detected in the experiment
labeled_components = ['ACH', 'ADGH', 'ACDI', 'ADF', 'ABEI', 'ABGI', 'ADEF', 'AEHI', 'AFHI', 'ACEF', 'ADFH', 'ABCE', 'ABCD', 'ACEG', 'AFI', 'ADFG', 'ABCG', 'ACE', 'ACD', 'AEFH', 'ACFG', 'AEFG', 'AEFI', 'AC', 'AEH', 'ABEH', 'ABGH', 'ADEH', 'ADHI', 'ACFI', 'ABI', 'AG', 'ACDE', 'ABFG', 'ACEH', 'ABDH', 'AFGH', 'AF', 'ABG', 'A', 'ACG', 'ADG', 'ACDH', 'AEF', 'ADEI', 'ACFH', 'ABC', 'ABDG', 'ABH', 'ACHI', 'AFG', 'ADFI', 'ABD', 'AGHI', 'ACGH', 'AE', 'AEI', 'ACDG', 'ABCI', 'AGI', 'ABEF', 'AEGH', 'ACEI', 'ABDI', 'AHI', 'ABFI', 'AFH', 'ADH', 'AD', 'AFGI', 'AB', 'ADE', 'ABDE', 'ACI', 'ABCF', 'ABF', 'AEGI', 'ABEG', 'ADI', 'ADGI', 'ACDF', 'ABFH', 'ABHI', 'ABE', 'ADEG', 'ACF', 'AH', 'AEG', 'AGH', 'ACGI', 'ABCH', 'AI', 'ABDF'] 

def system_equations(concentrations, state):
    """
    The equilibrium equations for this system. If an input result in the zero
    vector, that input is a solution to the system.
    """
    # Potential solution of the system
    B = concentrations[0]
    F = concentrations[1]
    G = concentrations[2]
    A = concentrations[3]
    E = concentrations[4]
    I = concentrations[5]
    D = concentrations[6]
    H = concentrations[7]
    C = concentrations[8]

    # Readability
    A_tot = state.A_tot
    B_tot = state.B_tot
    C_tot = state.C_tot
    D_tot = state.D_tot
    E_tot = state.E_tot
    F_tot = state.F_tot
    G_tot = state.G_tot
    H_tot = state.H_tot
    I_tot = state.I_tot
    Kd = state.Kd

    result = np.zeros(9)
    result[0] = (A*B*C*D/Kd**3 + A*B*C*E/Kd**3 + A*B*C*F/Kd**3 + A*B*C*G/Kd**3 + A*B*C*H/Kd**3 + A*B*C*I/Kd**3 + A*B*C/Kd**2 + A*B*D*E/Kd**3 + A*B*D*F/Kd**3 + A*B*D*G/Kd**3 + A*B*D*H/Kd**3 + A*B*D*I/Kd**3 + A*B*D/Kd**2 + A*B*E*F/Kd**3 + A*B*E*G/Kd**3 + A*B*E*H/Kd**3 + A*B*E*I/Kd**3 + A*B*E/Kd**2 + A*B*F*G/Kd**3 + A*B*F*H/Kd**3 + A*B*F*I/Kd**3 + A*B*F/Kd**2 + A*B*G*H/Kd**3 + A*B*G*I/Kd**3 + A*B*G/Kd**2 + A*B*H*I/Kd**3 + A*B*H/Kd**2 + A*B*I/Kd**2 + A*B/Kd + B*C*D*E/Kd**3 + B*C*D*F/Kd**3 + B*C*D*G/Kd**3 + B*C*D*H/Kd**3 + B*C*D*I/Kd**3 + B*C*D/Kd**2 + B*C*E*F/Kd**3 + B*C*E*G/Kd**3 + B*C*E*H/Kd**3 + B*C*E*I/Kd**3 + B*C*E/Kd**2 + B*C*F*G/Kd**3 + B*C*F*H/Kd**3 + B*C*F*I/Kd**3 + B*C*F/Kd**2 + B*C*G*H/Kd**3 + B*C*G*I/Kd**3 + B*C*G/Kd**2 + B*C*H*I/Kd**3 + B*C*H/Kd**2 + B*C*I/Kd**2 + B*C/Kd + B*D*E*F/Kd**3 + B*D*E*G/Kd**3 + B*D*E*H/Kd**3 + B*D*E*I/Kd**3 + B*D*E/Kd**2 + B*D*F*G/Kd**3 + B*D*F*H/Kd**3 + B*D*F*I/Kd**3 + B*D*F/Kd**2 + B*D*G*H/Kd**3 + B*D*G*I/Kd**3 + B*D*G/Kd**2 + B*D*H*I/Kd**3 + B*D*H/Kd**2 + B*D*I/Kd**2 + B*D/Kd + B*E*F*G/Kd**3 + B*E*F*H/Kd**3 + B*E*F*I/Kd**3 + B*E*F/Kd**2 + B*E*G*H/Kd**3 + B*E*G*I/Kd**3 + B*E*G/Kd**2 + B*E*H*I/Kd**3 + B*E*H/Kd**2 + B*E*I/Kd**2 + B*E/Kd + B*F*G*H/Kd**3 + B*F*G*I/Kd**3 + B*F*G/Kd**2 + B*F*H*I/Kd**3 + B*F*H/Kd**2 + B*F*I/Kd**2 + B*F/Kd + B*G*H*I/Kd**3 + B*G*H/Kd**2 + B*G*I/Kd**2 + B*G/Kd + B*H*I/Kd**2 + B*H/Kd + B*I/Kd + B - B_tot) / B_tot
    result[1] = (A*B*C*F/Kd**3 + A*B*D*F/Kd**3 + A*B*E*F/Kd**3 + A*B*F*G/Kd**3 + A*B*F*H/Kd**3 + A*B*F*I/Kd**3 + A*B*F/Kd**2 + A*C*D*F/Kd**3 + A*C*E*F/Kd**3 + A*C*F*G/Kd**3 + A*C*F*H/Kd**3 + A*C*F*I/Kd**3 + A*C*F/Kd**2 + A*D*E*F/Kd**3 + A*D*F*G/Kd**3 + A*D*F*H/Kd**3 + A*D*F*I/Kd**3 + A*D*F/Kd**2 + A*E*F*G/Kd**3 + A*E*F*H/Kd**3 + A*E*F*I/Kd**3 + A*E*F/Kd**2 + A*F*G*H/Kd**3 + A*F*G*I/Kd**3 + A*F*G/Kd**2 + A*F*H*I/Kd**3 + A*F*H/Kd**2 + A*F*I/Kd**2 + A*F/Kd + B*C*D*F/Kd**3 + B*C*E*F/Kd**3 + B*C*F*G/Kd**3 + B*C*F*H/Kd**3 + B*C*F*I/Kd**3 + B*C*F/Kd**2 + B*D*E*F/Kd**3 + B*D*F*G/Kd**3 + B*D*F*H/Kd**3 + B*D*F*I/Kd**3 + B*D*F/Kd**2 + B*E*F*G/Kd**3 + B*E*F*H/Kd**3 + B*E*F*I/Kd**3 + B*E*F/Kd**2 + B*F*G*H/Kd**3 + B*F*G*I/Kd**3 + B*F*G/Kd**2 + B*F*H*I/Kd**3 + B*F*H/Kd**2 + B*F*I/Kd**2 + B*F/Kd + C*D*E*F/Kd**3 + C*D*F*G/Kd**3 + C*D*F*H/Kd**3 + C*D*F*I/Kd**3 + C*D*F/Kd**2 + C*E*F*G/Kd**3 + C*E*F*H/Kd**3 + C*E*F*I/Kd**3 + C*E*F/Kd**2 + C*F*G*H/Kd**3 + C*F*G*I/Kd**3 + C*F*G/Kd**2 + C*F*H*I/Kd**3 + C*F*H/Kd**2 + C*F*I/Kd**2 + C*F/Kd + D*E*F*G/Kd**3 + D*E*F*H/Kd**3 + D*E*F*I/Kd**3 + D*E*F/Kd**2 + D*F*G*H/Kd**3 + D*F*G*I/Kd**3 + D*F*G/Kd**2 + D*F*H*I/Kd**3 + D*F*H/Kd**2 + D*F*I/Kd**2 + D*F/Kd + E*F*G*H/Kd**3 + E*F*G*I/Kd**3 + E*F*G/Kd**2 + E*F*H*I/Kd**3 + E*F*H/Kd**2 + E*F*I/Kd**2 + E*F/Kd + F*G*H*I/Kd**3 + F*G*H/Kd**2 + F*G*I/Kd**2 + F*G/Kd + F*H*I/Kd**2 + F*H/Kd + F*I/Kd + F - F_tot) / F_tot
    result[2] = (A*B*C*G/Kd**3 + A*B*D*G/Kd**3 + A*B*E*G/Kd**3 + A*B*F*G/Kd**3 + A*B*G*H/Kd**3 + A*B*G*I/Kd**3 + A*B*G/Kd**2 + A*C*D*G/Kd**3 + A*C*E*G/Kd**3 + A*C*F*G/Kd**3 + A*C*G*H/Kd**3 + A*C*G*I/Kd**3 + A*C*G/Kd**2 + A*D*E*G/Kd**3 + A*D*F*G/Kd**3 + A*D*G*H/Kd**3 + A*D*G*I/Kd**3 + A*D*G/Kd**2 + A*E*F*G/Kd**3 + A*E*G*H/Kd**3 + A*E*G*I/Kd**3 + A*E*G/Kd**2 + A*F*G*H/Kd**3 + A*F*G*I/Kd**3 + A*F*G/Kd**2 + A*G*H*I/Kd**3 + A*G*H/Kd**2 + A*G*I/Kd**2 + A*G/Kd + B*C*D*G/Kd**3 + B*C*E*G/Kd**3 + B*C*F*G/Kd**3 + B*C*G*H/Kd**3 + B*C*G*I/Kd**3 + B*C*G/Kd**2 + B*D*E*G/Kd**3 + B*D*F*G/Kd**3 + B*D*G*H/Kd**3 + B*D*G*I/Kd**3 + B*D*G/Kd**2 + B*E*F*G/Kd**3 + B*E*G*H/Kd**3 + B*E*G*I/Kd**3 + B*E*G/Kd**2 + B*F*G*H/Kd**3 + B*F*G*I/Kd**3 + B*F*G/Kd**2 + B*G*H*I/Kd**3 + B*G*H/Kd**2 + B*G*I/Kd**2 + B*G/Kd + C*D*E*G/Kd**3 + C*D*F*G/Kd**3 + C*D*G*H/Kd**3 + C*D*G*I/Kd**3 + C*D*G/Kd**2 + C*E*F*G/Kd**3 + C*E*G*H/Kd**3 + C*E*G*I/Kd**3 + C*E*G/Kd**2 + C*F*G*H/Kd**3 + C*F*G*I/Kd**3 + C*F*G/Kd**2 + C*G*H*I/Kd**3 + C*G*H/Kd**2 + C*G*I/Kd**2 + C*G/Kd + D*E*F*G/Kd**3 + D*E*G*H/Kd**3 + D*E*G*I/Kd**3 + D*E*G/Kd**2 + D*F*G*H/Kd**3 + D*F*G*I/Kd**3 + D*F*G/Kd**2 + D*G*H*I/Kd**3 + D*G*H/Kd**2 + D*G*I/Kd**2 + D*G/Kd + E*F*G*H/Kd**3 + E*F*G*I/Kd**3 + E*F*G/Kd**2 + E*G*H*I/Kd**3 + E*G*H/Kd**2 + E*G*I/Kd**2 + E*G/Kd + F*G*H*I/Kd**3 + F*G*H/Kd**2 + F*G*I/Kd**2 + F*G/Kd + G*H*I/Kd**2 + G*H/Kd + G*I/Kd + G - G_tot) / G_tot
    result[3] = (A*B*C*D/Kd**3 + A*B*C*E/Kd**3 + A*B*C*F/Kd**3 + A*B*C*G/Kd**3 + A*B*C*H/Kd**3 + A*B*C*I/Kd**3 + A*B*C/Kd**2 + A*B*D*E/Kd**3 + A*B*D*F/Kd**3 + A*B*D*G/Kd**3 + A*B*D*H/Kd**3 + A*B*D*I/Kd**3 + A*B*D/Kd**2 + A*B*E*F/Kd**3 + A*B*E*G/Kd**3 + A*B*E*H/Kd**3 + A*B*E*I/Kd**3 + A*B*E/Kd**2 + A*B*F*G/Kd**3 + A*B*F*H/Kd**3 + A*B*F*I/Kd**3 + A*B*F/Kd**2 + A*B*G*H/Kd**3 + A*B*G*I/Kd**3 + A*B*G/Kd**2 + A*B*H*I/Kd**3 + A*B*H/Kd**2 + A*B*I/Kd**2 + A*B/Kd + A*C*D*E/Kd**3 + A*C*D*F/Kd**3 + A*C*D*G/Kd**3 + A*C*D*H/Kd**3 + A*C*D*I/Kd**3 + A*C*D/Kd**2 + A*C*E*F/Kd**3 + A*C*E*G/Kd**3 + A*C*E*H/Kd**3 + A*C*E*I/Kd**3 + A*C*E/Kd**2 + A*C*F*G/Kd**3 + A*C*F*H/Kd**3 + A*C*F*I/Kd**3 + A*C*F/Kd**2 + A*C*G*H/Kd**3 + A*C*G*I/Kd**3 + A*C*G/Kd**2 + A*C*H*I/Kd**3 + A*C*H/Kd**2 + A*C*I/Kd**2 + A*C/Kd + A*D*E*F/Kd**3 + A*D*E*G/Kd**3 + A*D*E*H/Kd**3 + A*D*E*I/Kd**3 + A*D*E/Kd**2 + A*D*F*G/Kd**3 + A*D*F*H/Kd**3 + A*D*F*I/Kd**3 + A*D*F/Kd**2 + A*D*G*H/Kd**3 + A*D*G*I/Kd**3 + A*D*G/Kd**2 + A*D*H*I/Kd**3 + A*D*H/Kd**2 + A*D*I/Kd**2 + A*D/Kd + A*E*F*G/Kd**3 + A*E*F*H/Kd**3 + A*E*F*I/Kd**3 + A*E*F/Kd**2 + A*E*G*H/Kd**3 + A*E*G*I/Kd**3 + A*E*G/Kd**2 + A*E*H*I/Kd**3 + A*E*H/Kd**2 + A*E*I/Kd**2 + A*E/Kd + A*F*G*H/Kd**3 + A*F*G*I/Kd**3 + A*F*G/Kd**2 + A*F*H*I/Kd**3 + A*F*H/Kd**2 + A*F*I/Kd**2 + A*F/Kd + A*G*H*I/Kd**3 + A*G*H/Kd**2 + A*G*I/Kd**2 + A*G/Kd + A*H*I/Kd**2 + A*H/Kd + A*I/Kd + A - A_tot) / A_tot
    result[4] = (A*B*C*E/Kd**3 + A*B*D*E/Kd**3 + A*B*E*F/Kd**3 + A*B*E*G/Kd**3 + A*B*E*H/Kd**3 + A*B*E*I/Kd**3 + A*B*E/Kd**2 + A*C*D*E/Kd**3 + A*C*E*F/Kd**3 + A*C*E*G/Kd**3 + A*C*E*H/Kd**3 + A*C*E*I/Kd**3 + A*C*E/Kd**2 + A*D*E*F/Kd**3 + A*D*E*G/Kd**3 + A*D*E*H/Kd**3 + A*D*E*I/Kd**3 + A*D*E/Kd**2 + A*E*F*G/Kd**3 + A*E*F*H/Kd**3 + A*E*F*I/Kd**3 + A*E*F/Kd**2 + A*E*G*H/Kd**3 + A*E*G*I/Kd**3 + A*E*G/Kd**2 + A*E*H*I/Kd**3 + A*E*H/Kd**2 + A*E*I/Kd**2 + A*E/Kd + B*C*D*E/Kd**3 + B*C*E*F/Kd**3 + B*C*E*G/Kd**3 + B*C*E*H/Kd**3 + B*C*E*I/Kd**3 + B*C*E/Kd**2 + B*D*E*F/Kd**3 + B*D*E*G/Kd**3 + B*D*E*H/Kd**3 + B*D*E*I/Kd**3 + B*D*E/Kd**2 + B*E*F*G/Kd**3 + B*E*F*H/Kd**3 + B*E*F*I/Kd**3 + B*E*F/Kd**2 + B*E*G*H/Kd**3 + B*E*G*I/Kd**3 + B*E*G/Kd**2 + B*E*H*I/Kd**3 + B*E*H/Kd**2 + B*E*I/Kd**2 + B*E/Kd + C*D*E*F/Kd**3 + C*D*E*G/Kd**3 + C*D*E*H/Kd**3 + C*D*E*I/Kd**3 + C*D*E/Kd**2 + C*E*F*G/Kd**3 + C*E*F*H/Kd**3 + C*E*F*I/Kd**3 + C*E*F/Kd**2 + C*E*G*H/Kd**3 + C*E*G*I/Kd**3 + C*E*G/Kd**2 + C*E*H*I/Kd**3 + C*E*H/Kd**2 + C*E*I/Kd**2 + C*E/Kd + D*E*F*G/Kd**3 + D*E*F*H/Kd**3 + D*E*F*I/Kd**3 + D*E*F/Kd**2 + D*E*G*H/Kd**3 + D*E*G*I/Kd**3 + D*E*G/Kd**2 + D*E*H*I/Kd**3 + D*E*H/Kd**2 + D*E*I/Kd**2 + D*E/Kd + E*F*G*H/Kd**3 + E*F*G*I/Kd**3 + E*F*G/Kd**2 + E*F*H*I/Kd**3 + E*F*H/Kd**2 + E*F*I/Kd**2 + E*F/Kd + E*G*H*I/Kd**3 + E*G*H/Kd**2 + E*G*I/Kd**2 + E*G/Kd + E*H*I/Kd**2 + E*H/Kd + E*I/Kd + E - E_tot) / E_tot
    result[5] = (A*B*C*I/Kd**3 + A*B*D*I/Kd**3 + A*B*E*I/Kd**3 + A*B*F*I/Kd**3 + A*B*G*I/Kd**3 + A*B*H*I/Kd**3 + A*B*I/Kd**2 + A*C*D*I/Kd**3 + A*C*E*I/Kd**3 + A*C*F*I/Kd**3 + A*C*G*I/Kd**3 + A*C*H*I/Kd**3 + A*C*I/Kd**2 + A*D*E*I/Kd**3 + A*D*F*I/Kd**3 + A*D*G*I/Kd**3 + A*D*H*I/Kd**3 + A*D*I/Kd**2 + A*E*F*I/Kd**3 + A*E*G*I/Kd**3 + A*E*H*I/Kd**3 + A*E*I/Kd**2 + A*F*G*I/Kd**3 + A*F*H*I/Kd**3 + A*F*I/Kd**2 + A*G*H*I/Kd**3 + A*G*I/Kd**2 + A*H*I/Kd**2 + A*I/Kd + B*C*D*I/Kd**3 + B*C*E*I/Kd**3 + B*C*F*I/Kd**3 + B*C*G*I/Kd**3 + B*C*H*I/Kd**3 + B*C*I/Kd**2 + B*D*E*I/Kd**3 + B*D*F*I/Kd**3 + B*D*G*I/Kd**3 + B*D*H*I/Kd**3 + B*D*I/Kd**2 + B*E*F*I/Kd**3 + B*E*G*I/Kd**3 + B*E*H*I/Kd**3 + B*E*I/Kd**2 + B*F*G*I/Kd**3 + B*F*H*I/Kd**3 + B*F*I/Kd**2 + B*G*H*I/Kd**3 + B*G*I/Kd**2 + B*H*I/Kd**2 + B*I/Kd + C*D*E*I/Kd**3 + C*D*F*I/Kd**3 + C*D*G*I/Kd**3 + C*D*H*I/Kd**3 + C*D*I/Kd**2 + C*E*F*I/Kd**3 + C*E*G*I/Kd**3 + C*E*H*I/Kd**3 + C*E*I/Kd**2 + C*F*G*I/Kd**3 + C*F*H*I/Kd**3 + C*F*I/Kd**2 + C*G*H*I/Kd**3 + C*G*I/Kd**2 + C*H*I/Kd**2 + C*I/Kd + D*E*F*I/Kd**3 + D*E*G*I/Kd**3 + D*E*H*I/Kd**3 + D*E*I/Kd**2 + D*F*G*I/Kd**3 + D*F*H*I/Kd**3 + D*F*I/Kd**2 + D*G*H*I/Kd**3 + D*G*I/Kd**2 + D*H*I/Kd**2 + D*I/Kd + E*F*G*I/Kd**3 + E*F*H*I/Kd**3 + E*F*I/Kd**2 + E*G*H*I/Kd**3 + E*G*I/Kd**2 + E*H*I/Kd**2 + E*I/Kd + F*G*H*I/Kd**3 + F*G*I/Kd**2 + F*H*I/Kd**2 + F*I/Kd + G*H*I/Kd**2 + G*I/Kd + H*I/Kd + I - I_tot) / I_tot
    result[6] = (A*B*C*D/Kd**3 + A*B*D*E/Kd**3 + A*B*D*F/Kd**3 + A*B*D*G/Kd**3 + A*B*D*H/Kd**3 + A*B*D*I/Kd**3 + A*B*D/Kd**2 + A*C*D*E/Kd**3 + A*C*D*F/Kd**3 + A*C*D*G/Kd**3 + A*C*D*H/Kd**3 + A*C*D*I/Kd**3 + A*C*D/Kd**2 + A*D*E*F/Kd**3 + A*D*E*G/Kd**3 + A*D*E*H/Kd**3 + A*D*E*I/Kd**3 + A*D*E/Kd**2 + A*D*F*G/Kd**3 + A*D*F*H/Kd**3 + A*D*F*I/Kd**3 + A*D*F/Kd**2 + A*D*G*H/Kd**3 + A*D*G*I/Kd**3 + A*D*G/Kd**2 + A*D*H*I/Kd**3 + A*D*H/Kd**2 + A*D*I/Kd**2 + A*D/Kd + B*C*D*E/Kd**3 + B*C*D*F/Kd**3 + B*C*D*G/Kd**3 + B*C*D*H/Kd**3 + B*C*D*I/Kd**3 + B*C*D/Kd**2 + B*D*E*F/Kd**3 + B*D*E*G/Kd**3 + B*D*E*H/Kd**3 + B*D*E*I/Kd**3 + B*D*E/Kd**2 + B*D*F*G/Kd**3 + B*D*F*H/Kd**3 + B*D*F*I/Kd**3 + B*D*F/Kd**2 + B*D*G*H/Kd**3 + B*D*G*I/Kd**3 + B*D*G/Kd**2 + B*D*H*I/Kd**3 + B*D*H/Kd**2 + B*D*I/Kd**2 + B*D/Kd + C*D*E*F/Kd**3 + C*D*E*G/Kd**3 + C*D*E*H/Kd**3 + C*D*E*I/Kd**3 + C*D*E/Kd**2 + C*D*F*G/Kd**3 + C*D*F*H/Kd**3 + C*D*F*I/Kd**3 + C*D*F/Kd**2 + C*D*G*H/Kd**3 + C*D*G*I/Kd**3 + C*D*G/Kd**2 + C*D*H*I/Kd**3 + C*D*H/Kd**2 + C*D*I/Kd**2 + C*D/Kd + D*E*F*G/Kd**3 + D*E*F*H/Kd**3 + D*E*F*I/Kd**3 + D*E*F/Kd**2 + D*E*G*H/Kd**3 + D*E*G*I/Kd**3 + D*E*G/Kd**2 + D*E*H*I/Kd**3 + D*E*H/Kd**2 + D*E*I/Kd**2 + D*E/Kd + D*F*G*H/Kd**3 + D*F*G*I/Kd**3 + D*F*G/Kd**2 + D*F*H*I/Kd**3 + D*F*H/Kd**2 + D*F*I/Kd**2 + D*F/Kd + D*G*H*I/Kd**3 + D*G*H/Kd**2 + D*G*I/Kd**2 + D*G/Kd + D*H*I/Kd**2 + D*H/Kd + D*I/Kd + D - D_tot) / D_tot
    result[7] = (A*B*C*H/Kd**3 + A*B*D*H/Kd**3 + A*B*E*H/Kd**3 + A*B*F*H/Kd**3 + A*B*G*H/Kd**3 + A*B*H*I/Kd**3 + A*B*H/Kd**2 + A*C*D*H/Kd**3 + A*C*E*H/Kd**3 + A*C*F*H/Kd**3 + A*C*G*H/Kd**3 + A*C*H*I/Kd**3 + A*C*H/Kd**2 + A*D*E*H/Kd**3 + A*D*F*H/Kd**3 + A*D*G*H/Kd**3 + A*D*H*I/Kd**3 + A*D*H/Kd**2 + A*E*F*H/Kd**3 + A*E*G*H/Kd**3 + A*E*H*I/Kd**3 + A*E*H/Kd**2 + A*F*G*H/Kd**3 + A*F*H*I/Kd**3 + A*F*H/Kd**2 + A*G*H*I/Kd**3 + A*G*H/Kd**2 + A*H*I/Kd**2 + A*H/Kd + B*C*D*H/Kd**3 + B*C*E*H/Kd**3 + B*C*F*H/Kd**3 + B*C*G*H/Kd**3 + B*C*H*I/Kd**3 + B*C*H/Kd**2 + B*D*E*H/Kd**3 + B*D*F*H/Kd**3 + B*D*G*H/Kd**3 + B*D*H*I/Kd**3 + B*D*H/Kd**2 + B*E*F*H/Kd**3 + B*E*G*H/Kd**3 + B*E*H*I/Kd**3 + B*E*H/Kd**2 + B*F*G*H/Kd**3 + B*F*H*I/Kd**3 + B*F*H/Kd**2 + B*G*H*I/Kd**3 + B*G*H/Kd**2 + B*H*I/Kd**2 + B*H/Kd + C*D*E*H/Kd**3 + C*D*F*H/Kd**3 + C*D*G*H/Kd**3 + C*D*H*I/Kd**3 + C*D*H/Kd**2 + C*E*F*H/Kd**3 + C*E*G*H/Kd**3 + C*E*H*I/Kd**3 + C*E*H/Kd**2 + C*F*G*H/Kd**3 + C*F*H*I/Kd**3 + C*F*H/Kd**2 + C*G*H*I/Kd**3 + C*G*H/Kd**2 + C*H*I/Kd**2 + C*H/Kd + D*E*F*H/Kd**3 + D*E*G*H/Kd**3 + D*E*H*I/Kd**3 + D*E*H/Kd**2 + D*F*G*H/Kd**3 + D*F*H*I/Kd**3 + D*F*H/Kd**2 + D*G*H*I/Kd**3 + D*G*H/Kd**2 + D*H*I/Kd**2 + D*H/Kd + E*F*G*H/Kd**3 + E*F*H*I/Kd**3 + E*F*H/Kd**2 + E*G*H*I/Kd**3 + E*G*H/Kd**2 + E*H*I/Kd**2 + E*H/Kd + F*G*H*I/Kd**3 + F*G*H/Kd**2 + F*H*I/Kd**2 + F*H/Kd + G*H*I/Kd**2 + G*H/Kd + H*I/Kd + H - H_tot) / H_tot
    result[8] = (A*B*C*D/Kd**3 + A*B*C*E/Kd**3 + A*B*C*F/Kd**3 + A*B*C*G/Kd**3 + A*B*C*H/Kd**3 + A*B*C*I/Kd**3 + A*B*C/Kd**2 + A*C*D*E/Kd**3 + A*C*D*F/Kd**3 + A*C*D*G/Kd**3 + A*C*D*H/Kd**3 + A*C*D*I/Kd**3 + A*C*D/Kd**2 + A*C*E*F/Kd**3 + A*C*E*G/Kd**3 + A*C*E*H/Kd**3 + A*C*E*I/Kd**3 + A*C*E/Kd**2 + A*C*F*G/Kd**3 + A*C*F*H/Kd**3 + A*C*F*I/Kd**3 + A*C*F/Kd**2 + A*C*G*H/Kd**3 + A*C*G*I/Kd**3 + A*C*G/Kd**2 + A*C*H*I/Kd**3 + A*C*H/Kd**2 + A*C*I/Kd**2 + A*C/Kd + B*C*D*E/Kd**3 + B*C*D*F/Kd**3 + B*C*D*G/Kd**3 + B*C*D*H/Kd**3 + B*C*D*I/Kd**3 + B*C*D/Kd**2 + B*C*E*F/Kd**3 + B*C*E*G/Kd**3 + B*C*E*H/Kd**3 + B*C*E*I/Kd**3 + B*C*E/Kd**2 + B*C*F*G/Kd**3 + B*C*F*H/Kd**3 + B*C*F*I/Kd**3 + B*C*F/Kd**2 + B*C*G*H/Kd**3 + B*C*G*I/Kd**3 + B*C*G/Kd**2 + B*C*H*I/Kd**3 + B*C*H/Kd**2 + B*C*I/Kd**2 + B*C/Kd + C*D*E*F/Kd**3 + C*D*E*G/Kd**3 + C*D*E*H/Kd**3 + C*D*E*I/Kd**3 + C*D*E/Kd**2 + C*D*F*G/Kd**3 + C*D*F*H/Kd**3 + C*D*F*I/Kd**3 + C*D*F/Kd**2 + C*D*G*H/Kd**3 + C*D*G*I/Kd**3 + C*D*G/Kd**2 + C*D*H*I/Kd**3 + C*D*H/Kd**2 + C*D*I/Kd**2 + C*D/Kd + C*E*F*G/Kd**3 + C*E*F*H/Kd**3 + C*E*F*I/Kd**3 + C*E*F/Kd**2 + C*E*G*H/Kd**3 + C*E*G*I/Kd**3 + C*E*G/Kd**2 + C*E*H*I/Kd**3 + C*E*H/Kd**2 + C*E*I/Kd**2 + C*E/Kd + C*F*G*H/Kd**3 + C*F*G*I/Kd**3 + C*F*G/Kd**2 + C*F*H*I/Kd**3 + C*F*H/Kd**2 + C*F*I/Kd**2 + C*F/Kd + C*G*H*I/Kd**3 + C*G*H/Kd**2 + C*G*I/Kd**2 + C*G/Kd + C*H*I/Kd**2 + C*H/Kd + C*I/Kd + C - C_tot) / C_tot
    return result 


def update_state(solution, state):
    """
    Given a solution to the system_equations, update the state object to 
    reflect this solution.
    """
    # Independent variables
    state.B = solution[0]
    state.F = solution[1]
    state.G = solution[2]
    state.A = solution[3]
    state.E = solution[4]
    state.I = solution[5]
    state.D = solution[6]
    state.H = solution[7]
    state.C = solution[8]

    # Readability 
    A = state.A
    B = state.B
    C = state.C
    D = state.D
    E = state.E
    F = state.F
    G = state.G
    H = state.H
    I = state.I
    Kd = state.Kd

    # Dependent variables
    state.AB = A*B/Kd
    state.AC = A*C/Kd
    state.AD = A*D/Kd
    state.AE = A*E/Kd
    state.AF = A*F/Kd
    state.AG = A*G/Kd
    state.AH = A*H/Kd
    state.AI = A*I/Kd
    state.BC = B*C/Kd
    state.BD = B*D/Kd
    state.BE = B*E/Kd
    state.BF = B*F/Kd
    state.BG = B*G/Kd
    state.BH = B*H/Kd
    state.BI = B*I/Kd
    state.CD = C*D/Kd
    state.CE = C*E/Kd
    state.CF = C*F/Kd
    state.CG = C*G/Kd
    state.CH = C*H/Kd
    state.CI = C*I/Kd
    state.DE = D*E/Kd
    state.DF = D*F/Kd
    state.DG = D*G/Kd
    state.DH = D*H/Kd
    state.DI = D*I/Kd
    state.EF = E*F/Kd
    state.EG = E*G/Kd
    state.EH = E*H/Kd
    state.EI = E*I/Kd
    state.FG = F*G/Kd
    state.FH = F*H/Kd
    state.FI = F*I/Kd
    state.GH = G*H/Kd
    state.GI = G*I/Kd
    state.HI = H*I/Kd
    state.ABC = A*B*C/Kd**2
    state.ABD = A*B*D/Kd**2
    state.ABE = A*B*E/Kd**2
    state.ABF = A*B*F/Kd**2
    state.ABG = A*B*G/Kd**2
    state.ABH = A*B*H/Kd**2
    state.ABI = A*B*I/Kd**2
    state.ACD = A*C*D/Kd**2
    state.ACE = A*C*E/Kd**2
    state.ACF = A*C*F/Kd**2
    state.ACG = A*C*G/Kd**2
    state.ACH = A*C*H/Kd**2
    state.ACI = A*C*I/Kd**2
    state.ADE = A*D*E/Kd**2
    state.ADF = A*D*F/Kd**2
    state.ADG = A*D*G/Kd**2
    state.ADH = A*D*H/Kd**2
    state.ADI = A*D*I/Kd**2
    state.AEF = A*E*F/Kd**2
    state.AEG = A*E*G/Kd**2
    state.AEH = A*E*H/Kd**2
    state.AEI = A*E*I/Kd**2
    state.AFG = A*F*G/Kd**2
    state.AFH = A*F*H/Kd**2
    state.AFI = A*F*I/Kd**2
    state.AGH = A*G*H/Kd**2
    state.AGI = A*G*I/Kd**2
    state.AHI = A*H*I/Kd**2
    state.BCD = B*C*D/Kd**2
    state.BCE = B*C*E/Kd**2
    state.BCF = B*C*F/Kd**2
    state.BCG = B*C*G/Kd**2
    state.BCH = B*C*H/Kd**2
    state.BCI = B*C*I/Kd**2
    state.BDE = B*D*E/Kd**2
    state.BDF = B*D*F/Kd**2
    state.BDG = B*D*G/Kd**2
    state.BDH = B*D*H/Kd**2
    state.BDI = B*D*I/Kd**2
    state.BEF = B*E*F/Kd**2
    state.BEG = B*E*G/Kd**2
    state.BEH = B*E*H/Kd**2
    state.BEI = B*E*I/Kd**2
    state.BFG = B*F*G/Kd**2
    state.BFH = B*F*H/Kd**2
    state.BFI = B*F*I/Kd**2
    state.BGH = B*G*H/Kd**2
    state.BGI = B*G*I/Kd**2
    state.BHI = B*H*I/Kd**2
    state.CDE = C*D*E/Kd**2
    state.CDF = C*D*F/Kd**2
    state.CDG = C*D*G/Kd**2
    state.CDH = C*D*H/Kd**2
    state.CDI = C*D*I/Kd**2
    state.CEF = C*E*F/Kd**2
    state.CEG = C*E*G/Kd**2
    state.CEH = C*E*H/Kd**2
    state.CEI = C*E*I/Kd**2
    state.CFG = C*F*G/Kd**2
    state.CFH = C*F*H/Kd**2
    state.CFI = C*F*I/Kd**2
    state.CGH = C*G*H/Kd**2
    state.CGI = C*G*I/Kd**2
    state.CHI = C*H*I/Kd**2
    state.DEF = D*E*F/Kd**2
    state.DEG = D*E*G/Kd**2
    state.DEH = D*E*H/Kd**2
    state.DEI = D*E*I/Kd**2
    state.DFG = D*F*G/Kd**2
    state.DFH = D*F*H/Kd**2
    state.DFI = D*F*I/Kd**2
    state.DGH = D*G*H/Kd**2
    state.DGI = D*G*I/Kd**2
    state.DHI = D*H*I/Kd**2
    state.EFG = E*F*G/Kd**2
    state.EFH = E*F*H/Kd**2
    state.EFI = E*F*I/Kd**2
    state.EGH = E*G*H/Kd**2
    state.EGI = E*G*I/Kd**2
    state.EHI = E*H*I/Kd**2
    state.FGH = F*G*H/Kd**2
    state.FGI = F*G*I/Kd**2
    state.FHI = F*H*I/Kd**2
    state.GHI = G*H*I/Kd**2
    state.ABCD = A*B*C*D/Kd**3
    state.ABCE = A*B*C*E/Kd**3
    state.ABCF = A*B*C*F/Kd**3
    state.ABCG = A*B*C*G/Kd**3
    state.ABCH = A*B*C*H/Kd**3
    state.ABCI = A*B*C*I/Kd**3
    state.ABDE = A*B*D*E/Kd**3
    state.ABDF = A*B*D*F/Kd**3
    state.ABDG = A*B*D*G/Kd**3
    state.ABDH = A*B*D*H/Kd**3
    state.ABDI = A*B*D*I/Kd**3
    state.ABEF = A*B*E*F/Kd**3
    state.ABEG = A*B*E*G/Kd**3
    state.ABEH = A*B*E*H/Kd**3
    state.ABEI = A*B*E*I/Kd**3
    state.ABFG = A*B*F*G/Kd**3
    state.ABFH = A*B*F*H/Kd**3
    state.ABFI = A*B*F*I/Kd**3
    state.ABGH = A*B*G*H/Kd**3
    state.ABGI = A*B*G*I/Kd**3
    state.ABHI = A*B*H*I/Kd**3
    state.ACDE = A*C*D*E/Kd**3
    state.ACDF = A*C*D*F/Kd**3
    state.ACDG = A*C*D*G/Kd**3
    state.ACDH = A*C*D*H/Kd**3
    state.ACDI = A*C*D*I/Kd**3
    state.ACEF = A*C*E*F/Kd**3
    state.ACEG = A*C*E*G/Kd**3
    state.ACEH = A*C*E*H/Kd**3
    state.ACEI = A*C*E*I/Kd**3
    state.ACFG = A*C*F*G/Kd**3
    state.ACFH = A*C*F*H/Kd**3
    state.ACFI = A*C*F*I/Kd**3
    state.ACGH = A*C*G*H/Kd**3
    state.ACGI = A*C*G*I/Kd**3
    state.ACHI = A*C*H*I/Kd**3
    state.ADEF = A*D*E*F/Kd**3
    state.ADEG = A*D*E*G/Kd**3
    state.ADEH = A*D*E*H/Kd**3
    state.ADEI = A*D*E*I/Kd**3
    state.ADFG = A*D*F*G/Kd**3
    state.ADFH = A*D*F*H/Kd**3
    state.ADFI = A*D*F*I/Kd**3
    state.ADGH = A*D*G*H/Kd**3
    state.ADGI = A*D*G*I/Kd**3
    state.ADHI = A*D*H*I/Kd**3
    state.AEFG = A*E*F*G/Kd**3
    state.AEFH = A*E*F*H/Kd**3
    state.AEFI = A*E*F*I/Kd**3
    state.AEGH = A*E*G*H/Kd**3
    state.AEGI = A*E*G*I/Kd**3
    state.AEHI = A*E*H*I/Kd**3
    state.AFGH = A*F*G*H/Kd**3
    state.AFGI = A*F*G*I/Kd**3
    state.AFHI = A*F*H*I/Kd**3
    state.AGHI = A*G*H*I/Kd**3
    state.BCDE = B*C*D*E/Kd**3
    state.BCDF = B*C*D*F/Kd**3
    state.BCDG = B*C*D*G/Kd**3
    state.BCDH = B*C*D*H/Kd**3
    state.BCDI = B*C*D*I/Kd**3
    state.BCEF = B*C*E*F/Kd**3
    state.BCEG = B*C*E*G/Kd**3
    state.BCEH = B*C*E*H/Kd**3
    state.BCEI = B*C*E*I/Kd**3
    state.BCFG = B*C*F*G/Kd**3
    state.BCFH = B*C*F*H/Kd**3
    state.BCFI = B*C*F*I/Kd**3
    state.BCGH = B*C*G*H/Kd**3
    state.BCGI = B*C*G*I/Kd**3
    state.BCHI = B*C*H*I/Kd**3
    state.BDEF = B*D*E*F/Kd**3
    state.BDEG = B*D*E*G/Kd**3
    state.BDEH = B*D*E*H/Kd**3
    state.BDEI = B*D*E*I/Kd**3
    state.BDFG = B*D*F*G/Kd**3
    state.BDFH = B*D*F*H/Kd**3
    state.BDFI = B*D*F*I/Kd**3
    state.BDGH = B*D*G*H/Kd**3
    state.BDGI = B*D*G*I/Kd**3
    state.BDHI = B*D*H*I/Kd**3
    state.BEFG = B*E*F*G/Kd**3
    state.BEFH = B*E*F*H/Kd**3
    state.BEFI = B*E*F*I/Kd**3
    state.BEGH = B*E*G*H/Kd**3
    state.BEGI = B*E*G*I/Kd**3
    state.BEHI = B*E*H*I/Kd**3
    state.BFGH = B*F*G*H/Kd**3
    state.BFGI = B*F*G*I/Kd**3
    state.BFHI = B*F*H*I/Kd**3
    state.BGHI = B*G*H*I/Kd**3
    state.CDEF = C*D*E*F/Kd**3
    state.CDEG = C*D*E*G/Kd**3
    state.CDEH = C*D*E*H/Kd**3
    state.CDEI = C*D*E*I/Kd**3
    state.CDFG = C*D*F*G/Kd**3
    state.CDFH = C*D*F*H/Kd**3
    state.CDFI = C*D*F*I/Kd**3
    state.CDGH = C*D*G*H/Kd**3
    state.CDGI = C*D*G*I/Kd**3
    state.CDHI = C*D*H*I/Kd**3
    state.CEFG = C*E*F*G/Kd**3
    state.CEFH = C*E*F*H/Kd**3
    state.CEFI = C*E*F*I/Kd**3
    state.CEGH = C*E*G*H/Kd**3
    state.CEGI = C*E*G*I/Kd**3
    state.CEHI = C*E*H*I/Kd**3
    state.CFGH = C*F*G*H/Kd**3
    state.CFGI = C*F*G*I/Kd**3
    state.CFHI = C*F*H*I/Kd**3
    state.CGHI = C*G*H*I/Kd**3
    state.DEFG = D*E*F*G/Kd**3
    state.DEFH = D*E*F*H/Kd**3
    state.DEFI = D*E*F*I/Kd**3
    state.DEGH = D*E*G*H/Kd**3
    state.DEGI = D*E*G*I/Kd**3
    state.DEHI = D*E*H*I/Kd**3
    state.DFGH = D*F*G*H/Kd**3
    state.DFGI = D*F*G*I/Kd**3
    state.DFHI = D*F*H*I/Kd**3
    state.DGHI = D*G*H*I/Kd**3
    state.EFGH = E*F*G*H/Kd**3
    state.EFGI = E*F*G*I/Kd**3
    state.EFHI = E*F*H*I/Kd**3
    state.EGHI = E*G*H*I/Kd**3
    state.FGHI = F*G*H*I/Kd**3


def data_function(state):
    """
    Function to map state object to experimental data values.
    """
    # Readability
    A = state.A
    AB = state.AB
    ABC = state.ABC
    ABCD = state.ABCD
    ABCE = state.ABCE
    ABCF = state.ABCF
    ABCG = state.ABCG
    ABCH = state.ABCH
    ABCI = state.ABCI
    ABD = state.ABD
    ABDE = state.ABDE
    ABDF = state.ABDF
    ABDG = state.ABDG
    ABDH = state.ABDH
    ABDI = state.ABDI
    ABE = state.ABE
    ABEF = state.ABEF
    ABEG = state.ABEG
    ABEH = state.ABEH
    ABEI = state.ABEI
    ABF = state.ABF
    ABFG = state.ABFG
    ABFH = state.ABFH
    ABFI = state.ABFI
    ABG = state.ABG
    ABGH = state.ABGH
    ABGI = state.ABGI
    ABH = state.ABH
    ABHI = state.ABHI
    ABI = state.ABI
    AC = state.AC
    ACD = state.ACD
    ACDE = state.ACDE
    ACDF = state.ACDF
    ACDG = state.ACDG
    ACDH = state.ACDH
    ACDI = state.ACDI
    ACE = state.ACE
    ACEF = state.ACEF
    ACEG = state.ACEG
    ACEH = state.ACEH
    ACEI = state.ACEI
    ACF = state.ACF
    ACFG = state.ACFG
    ACFH = state.ACFH
    ACFI = state.ACFI
    ACG = state.ACG
    ACGH = state.ACGH
    ACGI = state.ACGI
    ACH = state.ACH
    ACHI = state.ACHI
    ACI = state.ACI
    AD = state.AD
    ADE = state.ADE
    ADEF = state.ADEF
    ADEG = state.ADEG
    ADEH = state.ADEH
    ADEI = state.ADEI
    ADF = state.ADF
    ADFG = state.ADFG
    ADFH = state.ADFH
    ADFI = state.ADFI
    ADG = state.ADG
    ADGH = state.ADGH
    ADGI = state.ADGI
    ADH = state.ADH
    ADHI = state.ADHI
    ADI = state.ADI
    AE = state.AE
    AEF = state.AEF
    AEFG = state.AEFG
    AEFH = state.AEFH
    AEFI = state.AEFI
    AEG = state.AEG
    AEGH = state.AEGH
    AEGI = state.AEGI
    AEH = state.AEH
    AEHI = state.AEHI
    AEI = state.AEI
    AF = state.AF
    AFG = state.AFG
    AFGH = state.AFGH
    AFGI = state.AFGI
    AFH = state.AFH
    AFHI = state.AFHI
    AFI = state.AFI
    AG = state.AG
    AGH = state.AGH
    AGHI = state.AGHI
    AGI = state.AGI
    AH = state.AH
    AHI = state.AHI
    AI = state.AI
    A_tot = state.A_tot
    data_max = state.data_max
    data_min = state.data_min

    return A*data_min/A_tot + data_max*(AB + ABC + ABCD + ABCE + ABCF + ABCG + ABCH + ABCI + ABD + ABDE + ABDF + ABDG + ABDH + ABDI + ABE + ABEF + ABEG + ABEH + ABEI + ABF + ABFG + ABFH + ABFI + ABG + ABGH + ABGI + ABH + ABHI + ABI + AC + ACD + ACDE + ACDF + ACDG + ACDH + ACDI + ACE + ACEF + ACEG + ACEH + ACEI + ACF + ACFG + ACFH + ACFI + ACG + ACGH + ACGI + ACH + ACHI + ACI + AD + ADE + ADEF + ADEG + ADEH + ADEI + ADF + ADFG + ADFH + ADFI + ADG + ADGH + ADGI + ADH + ADHI + ADI + AE + AEF + AEFG + AEFH + AEFI + AEG + AEGH + AEGI + AEH + AEHI + AEI + AF + AFG + AFGH + AFGI + AFH + AFHI + AFI + AG + AGH + AGHI + AGI + AH + AHI + AI)/A_tot


