"""
Model file created on 2021-08-20 14:22:04.106288 
Created using the automatic src/model_creator.py process.

Original input parameters
Equations:
A + B = AB; Kd
A + C = AC; Kd
A + D = AD; Kd
A + E = AE; Kd
A + F = AF; Kd
A + G = AG; Kd
A + H = AH; Kd
A + I = AI; Kd
A + J = AJ; Kd
B + C = BC; Kd
B + D = BD; Kd
B + E = BE; Kd
B + F = BF; Kd
B + G = BG; Kd
B + H = BH; Kd
B + I = BI; Kd
B + J = BJ; Kd
C + D = CD; Kd
C + E = CE; Kd
C + F = CF; Kd
C + G = CG; Kd
C + H = CH; Kd
C + I = CI; Kd
C + J = CJ; Kd
D + E = DE; Kd
D + F = DF; Kd
D + G = DG; Kd
D + H = DH; Kd
D + I = DI; Kd
D + J = DJ; Kd
E + F = EF; Kd
E + G = EG; Kd
E + H = EH; Kd
E + I = EI; Kd
E + J = EJ; Kd
F + G = FG; Kd
F + H = FH; Kd
F + I = FI; Kd
F + J = FJ; Kd
G + H = GH; Kd
G + I = GI; Kd
G + J = GJ; Kd
H + I = HI; Kd
H + J = HJ; Kd
I + J = IJ; Kd
AB + C = ABC; Kd
AB + D = ABD; Kd
AB + E = ABE; Kd
AB + F = ABF; Kd
AB + G = ABG; Kd
AB + H = ABH; Kd
AB + I = ABI; Kd
AB + J = ABJ; Kd
AC + D = ACD; Kd
AC + E = ACE; Kd
AC + F = ACF; Kd
AC + G = ACG; Kd
AC + H = ACH; Kd
AC + I = ACI; Kd
AC + J = ACJ; Kd
AD + E = ADE; Kd
AD + F = ADF; Kd
AD + G = ADG; Kd
AD + H = ADH; Kd
AD + I = ADI; Kd
AD + J = ADJ; Kd
AE + F = AEF; Kd
AE + G = AEG; Kd
AE + H = AEH; Kd
AE + I = AEI; Kd
AE + J = AEJ; Kd
AF + G = AFG; Kd
AF + H = AFH; Kd
AF + I = AFI; Kd
AF + J = AFJ; Kd
AG + H = AGH; Kd
AG + I = AGI; Kd
AG + J = AGJ; Kd
AH + I = AHI; Kd
AH + J = AHJ; Kd
AI + J = AIJ; Kd
BC + D = BCD; Kd
BC + E = BCE; Kd
BC + F = BCF; Kd
BC + G = BCG; Kd
BC + H = BCH; Kd
BC + I = BCI; Kd
BC + J = BCJ; Kd
BD + E = BDE; Kd
BD + F = BDF; Kd
BD + G = BDG; Kd
BD + H = BDH; Kd
BD + I = BDI; Kd
BD + J = BDJ; Kd
BE + F = BEF; Kd
BE + G = BEG; Kd
BE + H = BEH; Kd
BE + I = BEI; Kd
BE + J = BEJ; Kd
BF + G = BFG; Kd
BF + H = BFH; Kd
BF + I = BFI; Kd
BF + J = BFJ; Kd
BG + H = BGH; Kd
BG + I = BGI; Kd
BG + J = BGJ; Kd
BH + I = BHI; Kd
BH + J = BHJ; Kd
BI + J = BIJ; Kd
CD + E = CDE; Kd
CD + F = CDF; Kd
CD + G = CDG; Kd
CD + H = CDH; Kd
CD + I = CDI; Kd
CD + J = CDJ; Kd
CE + F = CEF; Kd
CE + G = CEG; Kd
CE + H = CEH; Kd
CE + I = CEI; Kd
CE + J = CEJ; Kd
CF + G = CFG; Kd
CF + H = CFH; Kd
CF + I = CFI; Kd
CF + J = CFJ; Kd
CG + H = CGH; Kd
CG + I = CGI; Kd
CG + J = CGJ; Kd
CH + I = CHI; Kd
CH + J = CHJ; Kd
CI + J = CIJ; Kd
DE + F = DEF; Kd
DE + G = DEG; Kd
DE + H = DEH; Kd
DE + I = DEI; Kd
DE + J = DEJ; Kd
DF + G = DFG; Kd
DF + H = DFH; Kd
DF + I = DFI; Kd
DF + J = DFJ; Kd
DG + H = DGH; Kd
DG + I = DGI; Kd
DG + J = DGJ; Kd
DH + I = DHI; Kd
DH + J = DHJ; Kd
DI + J = DIJ; Kd
EF + G = EFG; Kd
EF + H = EFH; Kd
EF + I = EFI; Kd
EF + J = EFJ; Kd
EG + H = EGH; Kd
EG + I = EGI; Kd
EG + J = EGJ; Kd
EH + I = EHI; Kd
EH + J = EHJ; Kd
EI + J = EIJ; Kd
FG + H = FGH; Kd
FG + I = FGI; Kd
FG + J = FGJ; Kd
FH + I = FHI; Kd
FH + J = FHJ; Kd
FI + J = FIJ; Kd
GH + I = GHI; Kd
GH + J = GHJ; Kd
GI + J = GIJ; Kd
HI + J = HIJ; Kd
ABC + D = ABCD; Kd
ABC + E = ABCE; Kd
ABC + F = ABCF; Kd
ABC + G = ABCG; Kd
ABC + H = ABCH; Kd
ABC + I = ABCI; Kd
ABC + J = ABCJ; Kd
ABD + E = ABDE; Kd
ABD + F = ABDF; Kd
ABD + G = ABDG; Kd
ABD + H = ABDH; Kd
ABD + I = ABDI; Kd
ABD + J = ABDJ; Kd
ABE + F = ABEF; Kd
ABE + G = ABEG; Kd
ABE + H = ABEH; Kd
ABE + I = ABEI; Kd
ABE + J = ABEJ; Kd
ABF + G = ABFG; Kd
ABF + H = ABFH; Kd
ABF + I = ABFI; Kd
ABF + J = ABFJ; Kd
ABG + H = ABGH; Kd
ABG + I = ABGI; Kd
ABG + J = ABGJ; Kd
ABH + I = ABHI; Kd
ABH + J = ABHJ; Kd
ABI + J = ABIJ; Kd
ACD + E = ACDE; Kd
ACD + F = ACDF; Kd
ACD + G = ACDG; Kd
ACD + H = ACDH; Kd
ACD + I = ACDI; Kd
ACD + J = ACDJ; Kd
ACE + F = ACEF; Kd
ACE + G = ACEG; Kd
ACE + H = ACEH; Kd
ACE + I = ACEI; Kd
ACE + J = ACEJ; Kd
ACF + G = ACFG; Kd
ACF + H = ACFH; Kd
ACF + I = ACFI; Kd
ACF + J = ACFJ; Kd
ACG + H = ACGH; Kd
ACG + I = ACGI; Kd
ACG + J = ACGJ; Kd
ACH + I = ACHI; Kd
ACH + J = ACHJ; Kd
ACI + J = ACIJ; Kd
ADE + F = ADEF; Kd
ADE + G = ADEG; Kd
ADE + H = ADEH; Kd
ADE + I = ADEI; Kd
ADE + J = ADEJ; Kd
ADF + G = ADFG; Kd
ADF + H = ADFH; Kd
ADF + I = ADFI; Kd
ADF + J = ADFJ; Kd
ADG + H = ADGH; Kd
ADG + I = ADGI; Kd
ADG + J = ADGJ; Kd
ADH + I = ADHI; Kd
ADH + J = ADHJ; Kd
ADI + J = ADIJ; Kd
AEF + G = AEFG; Kd
AEF + H = AEFH; Kd
AEF + I = AEFI; Kd
AEF + J = AEFJ; Kd
AEG + H = AEGH; Kd
AEG + I = AEGI; Kd
AEG + J = AEGJ; Kd
AEH + I = AEHI; Kd
AEH + J = AEHJ; Kd
AEI + J = AEIJ; Kd
AFG + H = AFGH; Kd
AFG + I = AFGI; Kd
AFG + J = AFGJ; Kd
AFH + I = AFHI; Kd
AFH + J = AFHJ; Kd
AFI + J = AFIJ; Kd
AGH + I = AGHI; Kd
AGH + J = AGHJ; Kd
AGI + J = AGIJ; Kd
AHI + J = AHIJ; Kd
BCD + E = BCDE; Kd
BCD + F = BCDF; Kd
BCD + G = BCDG; Kd
BCD + H = BCDH; Kd
BCD + I = BCDI; Kd
BCD + J = BCDJ; Kd
BCE + F = BCEF; Kd
BCE + G = BCEG; Kd
BCE + H = BCEH; Kd
BCE + I = BCEI; Kd
BCE + J = BCEJ; Kd
BCF + G = BCFG; Kd
BCF + H = BCFH; Kd
BCF + I = BCFI; Kd
BCF + J = BCFJ; Kd
BCG + H = BCGH; Kd
BCG + I = BCGI; Kd
BCG + J = BCGJ; Kd
BCH + I = BCHI; Kd
BCH + J = BCHJ; Kd
BCI + J = BCIJ; Kd
BDE + F = BDEF; Kd
BDE + G = BDEG; Kd
BDE + H = BDEH; Kd
BDE + I = BDEI; Kd
BDE + J = BDEJ; Kd
BDF + G = BDFG; Kd
BDF + H = BDFH; Kd
BDF + I = BDFI; Kd
BDF + J = BDFJ; Kd
BDG + H = BDGH; Kd
BDG + I = BDGI; Kd
BDG + J = BDGJ; Kd
BDH + I = BDHI; Kd
BDH + J = BDHJ; Kd
BDI + J = BDIJ; Kd
BEF + G = BEFG; Kd
BEF + H = BEFH; Kd
BEF + I = BEFI; Kd
BEF + J = BEFJ; Kd
BEG + H = BEGH; Kd
BEG + I = BEGI; Kd
BEG + J = BEGJ; Kd
BEH + I = BEHI; Kd
BEH + J = BEHJ; Kd
BEI + J = BEIJ; Kd
BFG + H = BFGH; Kd
BFG + I = BFGI; Kd
BFG + J = BFGJ; Kd
BFH + I = BFHI; Kd
BFH + J = BFHJ; Kd
BFI + J = BFIJ; Kd
BGH + I = BGHI; Kd
BGH + J = BGHJ; Kd
BGI + J = BGIJ; Kd
BHI + J = BHIJ; Kd
CDE + F = CDEF; Kd
CDE + G = CDEG; Kd
CDE + H = CDEH; Kd
CDE + I = CDEI; Kd
CDE + J = CDEJ; Kd
CDF + G = CDFG; Kd
CDF + H = CDFH; Kd
CDF + I = CDFI; Kd
CDF + J = CDFJ; Kd
CDG + H = CDGH; Kd
CDG + I = CDGI; Kd
CDG + J = CDGJ; Kd
CDH + I = CDHI; Kd
CDH + J = CDHJ; Kd
CDI + J = CDIJ; Kd
CEF + G = CEFG; Kd
CEF + H = CEFH; Kd
CEF + I = CEFI; Kd
CEF + J = CEFJ; Kd
CEG + H = CEGH; Kd
CEG + I = CEGI; Kd
CEG + J = CEGJ; Kd
CEH + I = CEHI; Kd
CEH + J = CEHJ; Kd
CEI + J = CEIJ; Kd
CFG + H = CFGH; Kd
CFG + I = CFGI; Kd
CFG + J = CFGJ; Kd
CFH + I = CFHI; Kd
CFH + J = CFHJ; Kd
CFI + J = CFIJ; Kd
CGH + I = CGHI; Kd
CGH + J = CGHJ; Kd
CGI + J = CGIJ; Kd
CHI + J = CHIJ; Kd
DEF + G = DEFG; Kd
DEF + H = DEFH; Kd
DEF + I = DEFI; Kd
DEF + J = DEFJ; Kd
DEG + H = DEGH; Kd
DEG + I = DEGI; Kd
DEG + J = DEGJ; Kd
DEH + I = DEHI; Kd
DEH + J = DEHJ; Kd
DEI + J = DEIJ; Kd
DFG + H = DFGH; Kd
DFG + I = DFGI; Kd
DFG + J = DFGJ; Kd
DFH + I = DFHI; Kd
DFH + J = DFHJ; Kd
DFI + J = DFIJ; Kd
DGH + I = DGHI; Kd
DGH + J = DGHJ; Kd
DGI + J = DGIJ; Kd
DHI + J = DHIJ; Kd
EFG + H = EFGH; Kd
EFG + I = EFGI; Kd
EFG + J = EFGJ; Kd
EFH + I = EFHI; Kd
EFH + J = EFHJ; Kd
EFI + J = EFIJ; Kd
EGH + I = EGHI; Kd
EGH + J = EGHJ; Kd
EGI + J = EGIJ; Kd
EHI + J = EHIJ; Kd
FGH + I = FGHI; Kd
FGH + J = FGHJ; Kd
FGI + J = FGIJ; Kd
FHI + J = FHIJ; Kd
GHI + J = GHIJ; Kd

Labeled specie: A
data_mode: anisotropy
"""

import numpy as np

# All variables for this model
variables = ['CDH', 'ACH', 'ADGH', 'EFH', 'BEHI', 'DEFI', 'DEFG', 'DFHI', 'DJ', 'CFJ', 'CDEF', 'ABEI', 'ADEF', 'AEHI', 'CEGJ', 'GI', 'ADFH', 'DHIJ', 'DFGI', 'CIJ', 'BGHI', 'CDGH', 'ABCD', 'HJ', 'FGJ', 'CFGI', 'ACEG', 'HIJ', 'BCHJ', 'GH', 'GIJ', 'ABCG', 'CFI', 'BCDJ', 'CJ', 'ACE', 'BEHJ', 'ACDJ', 'CDFG', 'BGJ', 'GJ', 'BDE', 'ABEJ', 'AEFH', 'BEFG', 'ACFG', 'EHIJ', 'AEFG', 'ADEJ', 'BDGH', 'BDG', 'FG', 'BDGI', 'CFHJ', 'CFHI', 'AFGJ', 'BEF', 'CDFJ', 'AEH', 'ABGH', 'ADEH', 'GHJ', 'ADHI', 'BJ', 'BDFH', 'DEHJ', 'BCEG', 'ACFI', 'CHI', 'AG', 'I', 'BEG', 'CDFI', 'EGHJ', 'ACEH', 'DFG', 'CFH', 'BHIJ', 'BEI', 'AFHJ', 'ABDH', 'EFGJ', 'EFIJ', 'BCE', 'BEFJ', 'BFG', 'FGHI', 'EFG', 'BFIJ', 'CFG', 'EFI', 'EFGI', 'CFGJ', 'BGH', 'BCD', 'BCDG', 'BEGH', 'ACG', 'BEGJ', 'DE', 'BDIJ', 'E', 'AEF', 'BDJ', 'BH', 'DFIJ', 'BFGJ', 'BCDE', 'ABDG', 'EFHJ', 'ACHI', 'BEIJ', 'AFG', 'BCG', 'ABHJ', 'CDHI', 'CHJ', 'ABD', 'AFJ', 'BCGH', 'BCDI', 'BE', 'BI', 'ABDJ', 'Kd', 'AGHI', 'ADIJ', 'CGIJ', 'ADHJ', 'CG', 'DGJ', 'BDEF', 'BFHJ', 'BDFJ', 'ABCI', 'BFHI', 'BDH', 'CE', 'ABIJ', 'CDIJ', 'BDI', 'BG', 'BCEJ', 'AEGJ', 'AHI', 'CEFI', 'CEIJ', 'DG', 'FH', 'GHIJ', 'ADJ', 'AFH', 'AHJ', 'DEH', 'AD', 'CGHI', 'AB', 'ADE', 'ABDE', 'BCDH', 'IJ', 'ACI', 'ABCF', 'BCGJ', 'AGIJ', 'CEHJ', 'ADI', 'G', 'EHJ', 'EIJ', 'ADGI', 'BFGI', 'DFI', 'DEIJ', 'AGJ', 'BGI', 'DEG', 'ACDF', 'ABCJ', 'CGH', 'DFH', 'ABFH', 'CDFH', 'BCEF', 'ACGJ', 'ACF', 'AGH', 'CGJ', 'ACGI', 'ABCH', 'DHJ', 'ABDF', 'CDEJ', 'CDI', 'BFH', 'CI', 'DGIJ', 'CEI', 'C', 'BCHI', 'EGIJ', 'ABJ', 'FHJ', 'ACDI', 'CDF', 'ADF', 'BC', 'DEJ', 'ABGI', 'F', 'AFHI', 'DFGH', 'ACEF', 'ABCE', 'BHI', 'AFI', 'CEH', 'AEFJ', 'ADFG', 'DH', 'CDEG', 'EGHI', 'CDG', 'ABGJ', 'BCH', 'BDFI', 'DI', 'BDEH', 'BCFG', 'CF', 'FIJ', 'J', 'EFHI', 'DFGJ', 'ACD', 'CEGH', 'BCI', 'CEFH', 'DFHJ', 'BDEG', 'ACFJ', 'CEFG', 'BF', 'B', 'AEFI', 'BEGI', 'AC', 'FI', 'ABEH', 'DIJ', 'BCEH', 'BFJ', 'EI', 'ABI', 'BEH', 'CD', 'ACDE', 'DGH', 'DEGJ', 'CDHJ', 'BCF', 'CGI', 'ABFG', 'BDHI', 'BDF', 'DEFH', 'AFGH', 'CGHJ', 'BGHJ', 'EF', 'CEGI', 'CDGI', 'AEHJ', 'AF', 'ABG', 'CEG', 'BEFH', 'A', 'ACDH', 'ADG', 'ACHJ', 'CDGJ', 'AEJ', 'DEFJ', 'EGJ', 'D', 'EGH', 'CEF', 'ADEI', 'DF', 'ACFH', 'CEHI', 'FGHJ', 'ACIJ', 'AJ', 'ABC', 'BHJ', 'BCFJ', 'DGHJ', 'CFIJ', 'ABH', 'BCFI', 'HI', 'BFGH', 'ADGJ', 'ACEJ', 'ACJ', 'DHI', 'GHI', 'ADFI', 'BCFH', 'BGIJ', 'H', 'BDEJ', 'AIJ', 'AE', 'BFI', 'ABFJ', 'DFJ', 'AEI', 'EHI', 'ACDG', 'AGI', 'DGI', 'BCJ', 'ABEF', 'AEGH', 'EFGH', 'BDFG', 'CDEI', 'CH', 'FHI', 'ACEI', 'EFJ', 'ABDI', 'BDHJ', 'BCGI', 'BDGJ', 'AHIJ', 'ABFI', 'AGHJ', 'CDEH', 'ADH', 'CEJ', 'DEHI', 'AFGI', 'EGI', 'FHIJ', 'DEGI', 'FGIJ', 'ADFJ', 'ABF', 'AEGI', 'ABEG', 'BCEI', 'BDEI', 'BCIJ', 'CDJ', 'EJ', 'CEFJ', 'BIJ', 'DGHI', 'EG', 'ABHI', 'DEI', 'ABE', 'EH', 'ADEG', 'AFIJ', 'AH', 'AEG', 'FGH', 'BEFI', 'CFGH', 'FGI', 'BCDF', 'FJ', 'AI', 'DEF', 'CDE', 'AEIJ', 'CHIJ', 'BEJ', 'ACGH', 'DEGH', 'BD', 'B_tot', 'F_tot', 'J_tot', 'G_tot', 'A_tot', 'E_tot', 'I_tot', 'D_tot', 'H_tot', 'C_tot']
# The species for which the concentrations need to be determined
# in order to solve the system. Will have the same order as system_equations.
independent_species = ['B', 'F', 'J', 'G', 'A', 'E', 'I', 'D', 'H', 'C']
# Species who's concentration can be determined from others
dependent_species = ['AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'CD', 'CE', 'CF', 'CG', 'CH', 'CI', 'CJ', 'DE', 'DF', 'DG', 'DH', 'DI', 'DJ', 'EF', 'EG', 'EH', 'EI', 'EJ', 'FG', 'FH', 'FI', 'FJ', 'GH', 'GI', 'GJ', 'HI', 'HJ', 'IJ', 'ABC', 'ABD', 'ABE', 'ABF', 'ABG', 'ABH', 'ABI', 'ABJ', 'ACD', 'ACE', 'ACF', 'ACG', 'ACH', 'ACI', 'ACJ', 'ADE', 'ADF', 'ADG', 'ADH', 'ADI', 'ADJ', 'AEF', 'AEG', 'AEH', 'AEI', 'AEJ', 'AFG', 'AFH', 'AFI', 'AFJ', 'AGH', 'AGI', 'AGJ', 'AHI', 'AHJ', 'AIJ', 'BCD', 'BCE', 'BCF', 'BCG', 'BCH', 'BCI', 'BCJ', 'BDE', 'BDF', 'BDG', 'BDH', 'BDI', 'BDJ', 'BEF', 'BEG', 'BEH', 'BEI', 'BEJ', 'BFG', 'BFH', 'BFI', 'BFJ', 'BGH', 'BGI', 'BGJ', 'BHI', 'BHJ', 'BIJ', 'CDE', 'CDF', 'CDG', 'CDH', 'CDI', 'CDJ', 'CEF', 'CEG', 'CEH', 'CEI', 'CEJ', 'CFG', 'CFH', 'CFI', 'CFJ', 'CGH', 'CGI', 'CGJ', 'CHI', 'CHJ', 'CIJ', 'DEF', 'DEG', 'DEH', 'DEI', 'DEJ', 'DFG', 'DFH', 'DFI', 'DFJ', 'DGH', 'DGI', 'DGJ', 'DHI', 'DHJ', 'DIJ', 'EFG', 'EFH', 'EFI', 'EFJ', 'EGH', 'EGI', 'EGJ', 'EHI', 'EHJ', 'EIJ', 'FGH', 'FGI', 'FGJ', 'FHI', 'FHJ', 'FIJ', 'GHI', 'GHJ', 'GIJ', 'HIJ', 'ABCD', 'ABCE', 'ABCF', 'ABCG', 'ABCH', 'ABCI', 'ABCJ', 'ABDE', 'ABDF', 'ABDG', 'ABDH', 'ABDI', 'ABDJ', 'ABEF', 'ABEG', 'ABEH', 'ABEI', 'ABEJ', 'ABFG', 'ABFH', 'ABFI', 'ABFJ', 'ABGH', 'ABGI', 'ABGJ', 'ABHI', 'ABHJ', 'ABIJ', 'ACDE', 'ACDF', 'ACDG', 'ACDH', 'ACDI', 'ACDJ', 'ACEF', 'ACEG', 'ACEH', 'ACEI', 'ACEJ', 'ACFG', 'ACFH', 'ACFI', 'ACFJ', 'ACGH', 'ACGI', 'ACGJ', 'ACHI', 'ACHJ', 'ACIJ', 'ADEF', 'ADEG', 'ADEH', 'ADEI', 'ADEJ', 'ADFG', 'ADFH', 'ADFI', 'ADFJ', 'ADGH', 'ADGI', 'ADGJ', 'ADHI', 'ADHJ', 'ADIJ', 'AEFG', 'AEFH', 'AEFI', 'AEFJ', 'AEGH', 'AEGI', 'AEGJ', 'AEHI', 'AEHJ', 'AEIJ', 'AFGH', 'AFGI', 'AFGJ', 'AFHI', 'AFHJ', 'AFIJ', 'AGHI', 'AGHJ', 'AGIJ', 'AHIJ', 'BCDE', 'BCDF', 'BCDG', 'BCDH', 'BCDI', 'BCDJ', 'BCEF', 'BCEG', 'BCEH', 'BCEI', 'BCEJ', 'BCFG', 'BCFH', 'BCFI', 'BCFJ', 'BCGH', 'BCGI', 'BCGJ', 'BCHI', 'BCHJ', 'BCIJ', 'BDEF', 'BDEG', 'BDEH', 'BDEI', 'BDEJ', 'BDFG', 'BDFH', 'BDFI', 'BDFJ', 'BDGH', 'BDGI', 'BDGJ', 'BDHI', 'BDHJ', 'BDIJ', 'BEFG', 'BEFH', 'BEFI', 'BEFJ', 'BEGH', 'BEGI', 'BEGJ', 'BEHI', 'BEHJ', 'BEIJ', 'BFGH', 'BFGI', 'BFGJ', 'BFHI', 'BFHJ', 'BFIJ', 'BGHI', 'BGHJ', 'BGIJ', 'BHIJ', 'CDEF', 'CDEG', 'CDEH', 'CDEI', 'CDEJ', 'CDFG', 'CDFH', 'CDFI', 'CDFJ', 'CDGH', 'CDGI', 'CDGJ', 'CDHI', 'CDHJ', 'CDIJ', 'CEFG', 'CEFH', 'CEFI', 'CEFJ', 'CEGH', 'CEGI', 'CEGJ', 'CEHI', 'CEHJ', 'CEIJ', 'CFGH', 'CFGI', 'CFGJ', 'CFHI', 'CFHJ', 'CFIJ', 'CGHI', 'CGHJ', 'CGIJ', 'CHIJ', 'DEFG', 'DEFH', 'DEFI', 'DEFJ', 'DEGH', 'DEGI', 'DEGJ', 'DEHI', 'DEHJ', 'DEIJ', 'DFGH', 'DFGI', 'DFGJ', 'DFHI', 'DFHJ', 'DFIJ', 'DGHI', 'DGHJ', 'DGIJ', 'DHIJ', 'EFGH', 'EFGI', 'EFGJ', 'EFHI', 'EFHJ', 'EFIJ', 'EGHI', 'EGHJ', 'EGIJ', 'EHIJ', 'FGHI', 'FGHJ', 'FGIJ', 'FHIJ', 'GHIJ']
# The constant terms in the model
constants = ['Kd']
# Which components are labeled / detected in the experiment
labeled_components = ['ACH', 'ADGH', 'ABEI', 'ADEF', 'AEHI', 'ADFH', 'ABCD', 'ACEG', 'ABCG', 'ACE', 'ACDJ', 'ABEJ', 'AEFH', 'ACFG', 'AEFG', 'ADEJ', 'AFGJ', 'AEH', 'ABGH', 'ADEH', 'ADHI', 'ACFI', 'AG', 'ACEH', 'AFHJ', 'ABDH', 'ACG', 'AEF', 'ABDG', 'ACHI', 'AFG', 'ABHJ', 'ABD', 'AFJ', 'ABDJ', 'AGHI', 'ADIJ', 'ADHJ', 'ABCI', 'ABIJ', 'AEGJ', 'AHI', 'ADJ', 'AFH', 'AHJ', 'AD', 'AB', 'ADE', 'ABDE', 'ACI', 'ABCF', 'AGIJ', 'ADI', 'ADGI', 'AGJ', 'ACDF', 'ABCJ', 'ABFH', 'ACGJ', 'ACF', 'AGH', 'ACGI', 'ABCH', 'ABDF', 'ABJ', 'ACDI', 'ADF', 'ABGI', 'AFHI', 'ACEF', 'ABCE', 'AFI', 'AEFJ', 'ADFG', 'ABGJ', 'ACD', 'ACFJ', 'AEFI', 'AC', 'ABEH', 'ABI', 'ACDE', 'ABFG', 'AFGH', 'AEHJ', 'AF', 'ABG', 'A', 'ACDH', 'ADG', 'ACHJ', 'AEJ', 'ADEI', 'ACFH', 'ACIJ', 'AJ', 'ABC', 'ABH', 'ADGJ', 'ACEJ', 'ACJ', 'ADFI', 'AIJ', 'AE', 'ABFJ', 'AEI', 'ACDG', 'AGI', 'ABEF', 'AEGH', 'ACEI', 'ABDI', 'AHIJ', 'ABFI', 'AGHJ', 'ADH', 'AFGI', 'ADFJ', 'ABF', 'AEGI', 'ABEG', 'ABHI', 'ABE', 'ADEG', 'AFIJ', 'AH', 'AEG', 'AI', 'AEIJ', 'ACGH'] 

def system_equations(concentrations, state):
    """
    The equilibrium equations for this system. If an input result in the zero
    vector, that input is a solution to the system.
    """
    # Potential solution of the system
    B = concentrations[0]
    F = concentrations[1]
    J = concentrations[2]
    G = concentrations[3]
    A = concentrations[4]
    E = concentrations[5]
    I = concentrations[6]
    D = concentrations[7]
    H = concentrations[8]
    C = concentrations[9]

    # Readability
    A_tot = state.A_tot
    B_tot = state.B_tot
    C_tot = state.C_tot
    D_tot = state.D_tot
    E_tot = state.E_tot
    F_tot = state.F_tot
    G_tot = state.G_tot
    H_tot = state.H_tot
    I_tot = state.I_tot
    J_tot = state.J_tot
    Kd = state.Kd

    result = np.zeros(10)
    result[0] = (A*B*C*D/Kd**3 + A*B*C*E/Kd**3 + A*B*C*F/Kd**3 + A*B*C*G/Kd**3 + A*B*C*H/Kd**3 + A*B*C*I/Kd**3 + A*B*C*J/Kd**3 + A*B*C/Kd**2 + A*B*D*E/Kd**3 + A*B*D*F/Kd**3 + A*B*D*G/Kd**3 + A*B*D*H/Kd**3 + A*B*D*I/Kd**3 + A*B*D*J/Kd**3 + A*B*D/Kd**2 + A*B*E*F/Kd**3 + A*B*E*G/Kd**3 + A*B*E*H/Kd**3 + A*B*E*I/Kd**3 + A*B*E*J/Kd**3 + A*B*E/Kd**2 + A*B*F*G/Kd**3 + A*B*F*H/Kd**3 + A*B*F*I/Kd**3 + A*B*F*J/Kd**3 + A*B*F/Kd**2 + A*B*G*H/Kd**3 + A*B*G*I/Kd**3 + A*B*G*J/Kd**3 + A*B*G/Kd**2 + A*B*H*I/Kd**3 + A*B*H*J/Kd**3 + A*B*H/Kd**2 + A*B*I*J/Kd**3 + A*B*I/Kd**2 + A*B*J/Kd**2 + A*B/Kd + B*C*D*E/Kd**3 + B*C*D*F/Kd**3 + B*C*D*G/Kd**3 + B*C*D*H/Kd**3 + B*C*D*I/Kd**3 + B*C*D*J/Kd**3 + B*C*D/Kd**2 + B*C*E*F/Kd**3 + B*C*E*G/Kd**3 + B*C*E*H/Kd**3 + B*C*E*I/Kd**3 + B*C*E*J/Kd**3 + B*C*E/Kd**2 + B*C*F*G/Kd**3 + B*C*F*H/Kd**3 + B*C*F*I/Kd**3 + B*C*F*J/Kd**3 + B*C*F/Kd**2 + B*C*G*H/Kd**3 + B*C*G*I/Kd**3 + B*C*G*J/Kd**3 + B*C*G/Kd**2 + B*C*H*I/Kd**3 + B*C*H*J/Kd**3 + B*C*H/Kd**2 + B*C*I*J/Kd**3 + B*C*I/Kd**2 + B*C*J/Kd**2 + B*C/Kd + B*D*E*F/Kd**3 + B*D*E*G/Kd**3 + B*D*E*H/Kd**3 + B*D*E*I/Kd**3 + B*D*E*J/Kd**3 + B*D*E/Kd**2 + B*D*F*G/Kd**3 + B*D*F*H/Kd**3 + B*D*F*I/Kd**3 + B*D*F*J/Kd**3 + B*D*F/Kd**2 + B*D*G*H/Kd**3 + B*D*G*I/Kd**3 + B*D*G*J/Kd**3 + B*D*G/Kd**2 + B*D*H*I/Kd**3 + B*D*H*J/Kd**3 + B*D*H/Kd**2 + B*D*I*J/Kd**3 + B*D*I/Kd**2 + B*D*J/Kd**2 + B*D/Kd + B*E*F*G/Kd**3 + B*E*F*H/Kd**3 + B*E*F*I/Kd**3 + B*E*F*J/Kd**3 + B*E*F/Kd**2 + B*E*G*H/Kd**3 + B*E*G*I/Kd**3 + B*E*G*J/Kd**3 + B*E*G/Kd**2 + B*E*H*I/Kd**3 + B*E*H*J/Kd**3 + B*E*H/Kd**2 + B*E*I*J/Kd**3 + B*E*I/Kd**2 + B*E*J/Kd**2 + B*E/Kd + B*F*G*H/Kd**3 + B*F*G*I/Kd**3 + B*F*G*J/Kd**3 + B*F*G/Kd**2 + B*F*H*I/Kd**3 + B*F*H*J/Kd**3 + B*F*H/Kd**2 + B*F*I*J/Kd**3 + B*F*I/Kd**2 + B*F*J/Kd**2 + B*F/Kd + B*G*H*I/Kd**3 + B*G*H*J/Kd**3 + B*G*H/Kd**2 + B*G*I*J/Kd**3 + B*G*I/Kd**2 + B*G*J/Kd**2 + B*G/Kd + B*H*I*J/Kd**3 + B*H*I/Kd**2 + B*H*J/Kd**2 + B*H/Kd + B*I*J/Kd**2 + B*I/Kd + B*J/Kd + B - B_tot) / B_tot
    result[1] = (A*B*C*F/Kd**3 + A*B*D*F/Kd**3 + A*B*E*F/Kd**3 + A*B*F*G/Kd**3 + A*B*F*H/Kd**3 + A*B*F*I/Kd**3 + A*B*F*J/Kd**3 + A*B*F/Kd**2 + A*C*D*F/Kd**3 + A*C*E*F/Kd**3 + A*C*F*G/Kd**3 + A*C*F*H/Kd**3 + A*C*F*I/Kd**3 + A*C*F*J/Kd**3 + A*C*F/Kd**2 + A*D*E*F/Kd**3 + A*D*F*G/Kd**3 + A*D*F*H/Kd**3 + A*D*F*I/Kd**3 + A*D*F*J/Kd**3 + A*D*F/Kd**2 + A*E*F*G/Kd**3 + A*E*F*H/Kd**3 + A*E*F*I/Kd**3 + A*E*F*J/Kd**3 + A*E*F/Kd**2 + A*F*G*H/Kd**3 + A*F*G*I/Kd**3 + A*F*G*J/Kd**3 + A*F*G/Kd**2 + A*F*H*I/Kd**3 + A*F*H*J/Kd**3 + A*F*H/Kd**2 + A*F*I*J/Kd**3 + A*F*I/Kd**2 + A*F*J/Kd**2 + A*F/Kd + B*C*D*F/Kd**3 + B*C*E*F/Kd**3 + B*C*F*G/Kd**3 + B*C*F*H/Kd**3 + B*C*F*I/Kd**3 + B*C*F*J/Kd**3 + B*C*F/Kd**2 + B*D*E*F/Kd**3 + B*D*F*G/Kd**3 + B*D*F*H/Kd**3 + B*D*F*I/Kd**3 + B*D*F*J/Kd**3 + B*D*F/Kd**2 + B*E*F*G/Kd**3 + B*E*F*H/Kd**3 + B*E*F*I/Kd**3 + B*E*F*J/Kd**3 + B*E*F/Kd**2 + B*F*G*H/Kd**3 + B*F*G*I/Kd**3 + B*F*G*J/Kd**3 + B*F*G/Kd**2 + B*F*H*I/Kd**3 + B*F*H*J/Kd**3 + B*F*H/Kd**2 + B*F*I*J/Kd**3 + B*F*I/Kd**2 + B*F*J/Kd**2 + B*F/Kd + C*D*E*F/Kd**3 + C*D*F*G/Kd**3 + C*D*F*H/Kd**3 + C*D*F*I/Kd**3 + C*D*F*J/Kd**3 + C*D*F/Kd**2 + C*E*F*G/Kd**3 + C*E*F*H/Kd**3 + C*E*F*I/Kd**3 + C*E*F*J/Kd**3 + C*E*F/Kd**2 + C*F*G*H/Kd**3 + C*F*G*I/Kd**3 + C*F*G*J/Kd**3 + C*F*G/Kd**2 + C*F*H*I/Kd**3 + C*F*H*J/Kd**3 + C*F*H/Kd**2 + C*F*I*J/Kd**3 + C*F*I/Kd**2 + C*F*J/Kd**2 + C*F/Kd + D*E*F*G/Kd**3 + D*E*F*H/Kd**3 + D*E*F*I/Kd**3 + D*E*F*J/Kd**3 + D*E*F/Kd**2 + D*F*G*H/Kd**3 + D*F*G*I/Kd**3 + D*F*G*J/Kd**3 + D*F*G/Kd**2 + D*F*H*I/Kd**3 + D*F*H*J/Kd**3 + D*F*H/Kd**2 + D*F*I*J/Kd**3 + D*F*I/Kd**2 + D*F*J/Kd**2 + D*F/Kd + E*F*G*H/Kd**3 + E*F*G*I/Kd**3 + E*F*G*J/Kd**3 + E*F*G/Kd**2 + E*F*H*I/Kd**3 + E*F*H*J/Kd**3 + E*F*H/Kd**2 + E*F*I*J/Kd**3 + E*F*I/Kd**2 + E*F*J/Kd**2 + E*F/Kd + F*G*H*I/Kd**3 + F*G*H*J/Kd**3 + F*G*H/Kd**2 + F*G*I*J/Kd**3 + F*G*I/Kd**2 + F*G*J/Kd**2 + F*G/Kd + F*H*I*J/Kd**3 + F*H*I/Kd**2 + F*H*J/Kd**2 + F*H/Kd + F*I*J/Kd**2 + F*I/Kd + F*J/Kd + F - F_tot) / F_tot
    result[2] = (A*B*C*J/Kd**3 + A*B*D*J/Kd**3 + A*B*E*J/Kd**3 + A*B*F*J/Kd**3 + A*B*G*J/Kd**3 + A*B*H*J/Kd**3 + A*B*I*J/Kd**3 + A*B*J/Kd**2 + A*C*D*J/Kd**3 + A*C*E*J/Kd**3 + A*C*F*J/Kd**3 + A*C*G*J/Kd**3 + A*C*H*J/Kd**3 + A*C*I*J/Kd**3 + A*C*J/Kd**2 + A*D*E*J/Kd**3 + A*D*F*J/Kd**3 + A*D*G*J/Kd**3 + A*D*H*J/Kd**3 + A*D*I*J/Kd**3 + A*D*J/Kd**2 + A*E*F*J/Kd**3 + A*E*G*J/Kd**3 + A*E*H*J/Kd**3 + A*E*I*J/Kd**3 + A*E*J/Kd**2 + A*F*G*J/Kd**3 + A*F*H*J/Kd**3 + A*F*I*J/Kd**3 + A*F*J/Kd**2 + A*G*H*J/Kd**3 + A*G*I*J/Kd**3 + A*G*J/Kd**2 + A*H*I*J/Kd**3 + A*H*J/Kd**2 + A*I*J/Kd**2 + A*J/Kd + B*C*D*J/Kd**3 + B*C*E*J/Kd**3 + B*C*F*J/Kd**3 + B*C*G*J/Kd**3 + B*C*H*J/Kd**3 + B*C*I*J/Kd**3 + B*C*J/Kd**2 + B*D*E*J/Kd**3 + B*D*F*J/Kd**3 + B*D*G*J/Kd**3 + B*D*H*J/Kd**3 + B*D*I*J/Kd**3 + B*D*J/Kd**2 + B*E*F*J/Kd**3 + B*E*G*J/Kd**3 + B*E*H*J/Kd**3 + B*E*I*J/Kd**3 + B*E*J/Kd**2 + B*F*G*J/Kd**3 + B*F*H*J/Kd**3 + B*F*I*J/Kd**3 + B*F*J/Kd**2 + B*G*H*J/Kd**3 + B*G*I*J/Kd**3 + B*G*J/Kd**2 + B*H*I*J/Kd**3 + B*H*J/Kd**2 + B*I*J/Kd**2 + B*J/Kd + C*D*E*J/Kd**3 + C*D*F*J/Kd**3 + C*D*G*J/Kd**3 + C*D*H*J/Kd**3 + C*D*I*J/Kd**3 + C*D*J/Kd**2 + C*E*F*J/Kd**3 + C*E*G*J/Kd**3 + C*E*H*J/Kd**3 + C*E*I*J/Kd**3 + C*E*J/Kd**2 + C*F*G*J/Kd**3 + C*F*H*J/Kd**3 + C*F*I*J/Kd**3 + C*F*J/Kd**2 + C*G*H*J/Kd**3 + C*G*I*J/Kd**3 + C*G*J/Kd**2 + C*H*I*J/Kd**3 + C*H*J/Kd**2 + C*I*J/Kd**2 + C*J/Kd + D*E*F*J/Kd**3 + D*E*G*J/Kd**3 + D*E*H*J/Kd**3 + D*E*I*J/Kd**3 + D*E*J/Kd**2 + D*F*G*J/Kd**3 + D*F*H*J/Kd**3 + D*F*I*J/Kd**3 + D*F*J/Kd**2 + D*G*H*J/Kd**3 + D*G*I*J/Kd**3 + D*G*J/Kd**2 + D*H*I*J/Kd**3 + D*H*J/Kd**2 + D*I*J/Kd**2 + D*J/Kd + E*F*G*J/Kd**3 + E*F*H*J/Kd**3 + E*F*I*J/Kd**3 + E*F*J/Kd**2 + E*G*H*J/Kd**3 + E*G*I*J/Kd**3 + E*G*J/Kd**2 + E*H*I*J/Kd**3 + E*H*J/Kd**2 + E*I*J/Kd**2 + E*J/Kd + F*G*H*J/Kd**3 + F*G*I*J/Kd**3 + F*G*J/Kd**2 + F*H*I*J/Kd**3 + F*H*J/Kd**2 + F*I*J/Kd**2 + F*J/Kd + G*H*I*J/Kd**3 + G*H*J/Kd**2 + G*I*J/Kd**2 + G*J/Kd + H*I*J/Kd**2 + H*J/Kd + I*J/Kd + J - J_tot) / J_tot
    result[3] = (A*B*C*G/Kd**3 + A*B*D*G/Kd**3 + A*B*E*G/Kd**3 + A*B*F*G/Kd**3 + A*B*G*H/Kd**3 + A*B*G*I/Kd**3 + A*B*G*J/Kd**3 + A*B*G/Kd**2 + A*C*D*G/Kd**3 + A*C*E*G/Kd**3 + A*C*F*G/Kd**3 + A*C*G*H/Kd**3 + A*C*G*I/Kd**3 + A*C*G*J/Kd**3 + A*C*G/Kd**2 + A*D*E*G/Kd**3 + A*D*F*G/Kd**3 + A*D*G*H/Kd**3 + A*D*G*I/Kd**3 + A*D*G*J/Kd**3 + A*D*G/Kd**2 + A*E*F*G/Kd**3 + A*E*G*H/Kd**3 + A*E*G*I/Kd**3 + A*E*G*J/Kd**3 + A*E*G/Kd**2 + A*F*G*H/Kd**3 + A*F*G*I/Kd**3 + A*F*G*J/Kd**3 + A*F*G/Kd**2 + A*G*H*I/Kd**3 + A*G*H*J/Kd**3 + A*G*H/Kd**2 + A*G*I*J/Kd**3 + A*G*I/Kd**2 + A*G*J/Kd**2 + A*G/Kd + B*C*D*G/Kd**3 + B*C*E*G/Kd**3 + B*C*F*G/Kd**3 + B*C*G*H/Kd**3 + B*C*G*I/Kd**3 + B*C*G*J/Kd**3 + B*C*G/Kd**2 + B*D*E*G/Kd**3 + B*D*F*G/Kd**3 + B*D*G*H/Kd**3 + B*D*G*I/Kd**3 + B*D*G*J/Kd**3 + B*D*G/Kd**2 + B*E*F*G/Kd**3 + B*E*G*H/Kd**3 + B*E*G*I/Kd**3 + B*E*G*J/Kd**3 + B*E*G/Kd**2 + B*F*G*H/Kd**3 + B*F*G*I/Kd**3 + B*F*G*J/Kd**3 + B*F*G/Kd**2 + B*G*H*I/Kd**3 + B*G*H*J/Kd**3 + B*G*H/Kd**2 + B*G*I*J/Kd**3 + B*G*I/Kd**2 + B*G*J/Kd**2 + B*G/Kd + C*D*E*G/Kd**3 + C*D*F*G/Kd**3 + C*D*G*H/Kd**3 + C*D*G*I/Kd**3 + C*D*G*J/Kd**3 + C*D*G/Kd**2 + C*E*F*G/Kd**3 + C*E*G*H/Kd**3 + C*E*G*I/Kd**3 + C*E*G*J/Kd**3 + C*E*G/Kd**2 + C*F*G*H/Kd**3 + C*F*G*I/Kd**3 + C*F*G*J/Kd**3 + C*F*G/Kd**2 + C*G*H*I/Kd**3 + C*G*H*J/Kd**3 + C*G*H/Kd**2 + C*G*I*J/Kd**3 + C*G*I/Kd**2 + C*G*J/Kd**2 + C*G/Kd + D*E*F*G/Kd**3 + D*E*G*H/Kd**3 + D*E*G*I/Kd**3 + D*E*G*J/Kd**3 + D*E*G/Kd**2 + D*F*G*H/Kd**3 + D*F*G*I/Kd**3 + D*F*G*J/Kd**3 + D*F*G/Kd**2 + D*G*H*I/Kd**3 + D*G*H*J/Kd**3 + D*G*H/Kd**2 + D*G*I*J/Kd**3 + D*G*I/Kd**2 + D*G*J/Kd**2 + D*G/Kd + E*F*G*H/Kd**3 + E*F*G*I/Kd**3 + E*F*G*J/Kd**3 + E*F*G/Kd**2 + E*G*H*I/Kd**3 + E*G*H*J/Kd**3 + E*G*H/Kd**2 + E*G*I*J/Kd**3 + E*G*I/Kd**2 + E*G*J/Kd**2 + E*G/Kd + F*G*H*I/Kd**3 + F*G*H*J/Kd**3 + F*G*H/Kd**2 + F*G*I*J/Kd**3 + F*G*I/Kd**2 + F*G*J/Kd**2 + F*G/Kd + G*H*I*J/Kd**3 + G*H*I/Kd**2 + G*H*J/Kd**2 + G*H/Kd + G*I*J/Kd**2 + G*I/Kd + G*J/Kd + G - G_tot) / G_tot
    result[4] = (A*B*C*D/Kd**3 + A*B*C*E/Kd**3 + A*B*C*F/Kd**3 + A*B*C*G/Kd**3 + A*B*C*H/Kd**3 + A*B*C*I/Kd**3 + A*B*C*J/Kd**3 + A*B*C/Kd**2 + A*B*D*E/Kd**3 + A*B*D*F/Kd**3 + A*B*D*G/Kd**3 + A*B*D*H/Kd**3 + A*B*D*I/Kd**3 + A*B*D*J/Kd**3 + A*B*D/Kd**2 + A*B*E*F/Kd**3 + A*B*E*G/Kd**3 + A*B*E*H/Kd**3 + A*B*E*I/Kd**3 + A*B*E*J/Kd**3 + A*B*E/Kd**2 + A*B*F*G/Kd**3 + A*B*F*H/Kd**3 + A*B*F*I/Kd**3 + A*B*F*J/Kd**3 + A*B*F/Kd**2 + A*B*G*H/Kd**3 + A*B*G*I/Kd**3 + A*B*G*J/Kd**3 + A*B*G/Kd**2 + A*B*H*I/Kd**3 + A*B*H*J/Kd**3 + A*B*H/Kd**2 + A*B*I*J/Kd**3 + A*B*I/Kd**2 + A*B*J/Kd**2 + A*B/Kd + A*C*D*E/Kd**3 + A*C*D*F/Kd**3 + A*C*D*G/Kd**3 + A*C*D*H/Kd**3 + A*C*D*I/Kd**3 + A*C*D*J/Kd**3 + A*C*D/Kd**2 + A*C*E*F/Kd**3 + A*C*E*G/Kd**3 + A*C*E*H/Kd**3 + A*C*E*I/Kd**3 + A*C*E*J/Kd**3 + A*C*E/Kd**2 + A*C*F*G/Kd**3 + A*C*F*H/Kd**3 + A*C*F*I/Kd**3 + A*C*F*J/Kd**3 + A*C*F/Kd**2 + A*C*G*H/Kd**3 + A*C*G*I/Kd**3 + A*C*G*J/Kd**3 + A*C*G/Kd**2 + A*C*H*I/Kd**3 + A*C*H*J/Kd**3 + A*C*H/Kd**2 + A*C*I*J/Kd**3 + A*C*I/Kd**2 + A*C*J/Kd**2 + A*C/Kd + A*D*E*F/Kd**3 + A*D*E*G/Kd**3 + A*D*E*H/Kd**3 + A*D*E*I/Kd**3 + A*D*E*J/Kd**3 + A*D*E/Kd**2 + A*D*F*G/Kd**3 + A*D*F*H/Kd**3 + A*D*F*I/Kd**3 + A*D*F*J/Kd**3 + A*D*F/Kd**2 + A*D*G*H/Kd**3 + A*D*G*I/Kd**3 + A*D*G*J/Kd**3 + A*D*G/Kd**2 + A*D*H*I/Kd**3 + A*D*H*J/Kd**3 + A*D*H/Kd**2 + A*D*I*J/Kd**3 + A*D*I/Kd**2 + A*D*J/Kd**2 + A*D/Kd + A*E*F*G/Kd**3 + A*E*F*H/Kd**3 + A*E*F*I/Kd**3 + A*E*F*J/Kd**3 + A*E*F/Kd**2 + A*E*G*H/Kd**3 + A*E*G*I/Kd**3 + A*E*G*J/Kd**3 + A*E*G/Kd**2 + A*E*H*I/Kd**3 + A*E*H*J/Kd**3 + A*E*H/Kd**2 + A*E*I*J/Kd**3 + A*E*I/Kd**2 + A*E*J/Kd**2 + A*E/Kd + A*F*G*H/Kd**3 + A*F*G*I/Kd**3 + A*F*G*J/Kd**3 + A*F*G/Kd**2 + A*F*H*I/Kd**3 + A*F*H*J/Kd**3 + A*F*H/Kd**2 + A*F*I*J/Kd**3 + A*F*I/Kd**2 + A*F*J/Kd**2 + A*F/Kd + A*G*H*I/Kd**3 + A*G*H*J/Kd**3 + A*G*H/Kd**2 + A*G*I*J/Kd**3 + A*G*I/Kd**2 + A*G*J/Kd**2 + A*G/Kd + A*H*I*J/Kd**3 + A*H*I/Kd**2 + A*H*J/Kd**2 + A*H/Kd + A*I*J/Kd**2 + A*I/Kd + A*J/Kd + A - A_tot) / A_tot
    result[5] = (A*B*C*E/Kd**3 + A*B*D*E/Kd**3 + A*B*E*F/Kd**3 + A*B*E*G/Kd**3 + A*B*E*H/Kd**3 + A*B*E*I/Kd**3 + A*B*E*J/Kd**3 + A*B*E/Kd**2 + A*C*D*E/Kd**3 + A*C*E*F/Kd**3 + A*C*E*G/Kd**3 + A*C*E*H/Kd**3 + A*C*E*I/Kd**3 + A*C*E*J/Kd**3 + A*C*E/Kd**2 + A*D*E*F/Kd**3 + A*D*E*G/Kd**3 + A*D*E*H/Kd**3 + A*D*E*I/Kd**3 + A*D*E*J/Kd**3 + A*D*E/Kd**2 + A*E*F*G/Kd**3 + A*E*F*H/Kd**3 + A*E*F*I/Kd**3 + A*E*F*J/Kd**3 + A*E*F/Kd**2 + A*E*G*H/Kd**3 + A*E*G*I/Kd**3 + A*E*G*J/Kd**3 + A*E*G/Kd**2 + A*E*H*I/Kd**3 + A*E*H*J/Kd**3 + A*E*H/Kd**2 + A*E*I*J/Kd**3 + A*E*I/Kd**2 + A*E*J/Kd**2 + A*E/Kd + B*C*D*E/Kd**3 + B*C*E*F/Kd**3 + B*C*E*G/Kd**3 + B*C*E*H/Kd**3 + B*C*E*I/Kd**3 + B*C*E*J/Kd**3 + B*C*E/Kd**2 + B*D*E*F/Kd**3 + B*D*E*G/Kd**3 + B*D*E*H/Kd**3 + B*D*E*I/Kd**3 + B*D*E*J/Kd**3 + B*D*E/Kd**2 + B*E*F*G/Kd**3 + B*E*F*H/Kd**3 + B*E*F*I/Kd**3 + B*E*F*J/Kd**3 + B*E*F/Kd**2 + B*E*G*H/Kd**3 + B*E*G*I/Kd**3 + B*E*G*J/Kd**3 + B*E*G/Kd**2 + B*E*H*I/Kd**3 + B*E*H*J/Kd**3 + B*E*H/Kd**2 + B*E*I*J/Kd**3 + B*E*I/Kd**2 + B*E*J/Kd**2 + B*E/Kd + C*D*E*F/Kd**3 + C*D*E*G/Kd**3 + C*D*E*H/Kd**3 + C*D*E*I/Kd**3 + C*D*E*J/Kd**3 + C*D*E/Kd**2 + C*E*F*G/Kd**3 + C*E*F*H/Kd**3 + C*E*F*I/Kd**3 + C*E*F*J/Kd**3 + C*E*F/Kd**2 + C*E*G*H/Kd**3 + C*E*G*I/Kd**3 + C*E*G*J/Kd**3 + C*E*G/Kd**2 + C*E*H*I/Kd**3 + C*E*H*J/Kd**3 + C*E*H/Kd**2 + C*E*I*J/Kd**3 + C*E*I/Kd**2 + C*E*J/Kd**2 + C*E/Kd + D*E*F*G/Kd**3 + D*E*F*H/Kd**3 + D*E*F*I/Kd**3 + D*E*F*J/Kd**3 + D*E*F/Kd**2 + D*E*G*H/Kd**3 + D*E*G*I/Kd**3 + D*E*G*J/Kd**3 + D*E*G/Kd**2 + D*E*H*I/Kd**3 + D*E*H*J/Kd**3 + D*E*H/Kd**2 + D*E*I*J/Kd**3 + D*E*I/Kd**2 + D*E*J/Kd**2 + D*E/Kd + E*F*G*H/Kd**3 + E*F*G*I/Kd**3 + E*F*G*J/Kd**3 + E*F*G/Kd**2 + E*F*H*I/Kd**3 + E*F*H*J/Kd**3 + E*F*H/Kd**2 + E*F*I*J/Kd**3 + E*F*I/Kd**2 + E*F*J/Kd**2 + E*F/Kd + E*G*H*I/Kd**3 + E*G*H*J/Kd**3 + E*G*H/Kd**2 + E*G*I*J/Kd**3 + E*G*I/Kd**2 + E*G*J/Kd**2 + E*G/Kd + E*H*I*J/Kd**3 + E*H*I/Kd**2 + E*H*J/Kd**2 + E*H/Kd + E*I*J/Kd**2 + E*I/Kd + E*J/Kd + E - E_tot) / E_tot
    result[6] = (A*B*C*I/Kd**3 + A*B*D*I/Kd**3 + A*B*E*I/Kd**3 + A*B*F*I/Kd**3 + A*B*G*I/Kd**3 + A*B*H*I/Kd**3 + A*B*I*J/Kd**3 + A*B*I/Kd**2 + A*C*D*I/Kd**3 + A*C*E*I/Kd**3 + A*C*F*I/Kd**3 + A*C*G*I/Kd**3 + A*C*H*I/Kd**3 + A*C*I*J/Kd**3 + A*C*I/Kd**2 + A*D*E*I/Kd**3 + A*D*F*I/Kd**3 + A*D*G*I/Kd**3 + A*D*H*I/Kd**3 + A*D*I*J/Kd**3 + A*D*I/Kd**2 + A*E*F*I/Kd**3 + A*E*G*I/Kd**3 + A*E*H*I/Kd**3 + A*E*I*J/Kd**3 + A*E*I/Kd**2 + A*F*G*I/Kd**3 + A*F*H*I/Kd**3 + A*F*I*J/Kd**3 + A*F*I/Kd**2 + A*G*H*I/Kd**3 + A*G*I*J/Kd**3 + A*G*I/Kd**2 + A*H*I*J/Kd**3 + A*H*I/Kd**2 + A*I*J/Kd**2 + A*I/Kd + B*C*D*I/Kd**3 + B*C*E*I/Kd**3 + B*C*F*I/Kd**3 + B*C*G*I/Kd**3 + B*C*H*I/Kd**3 + B*C*I*J/Kd**3 + B*C*I/Kd**2 + B*D*E*I/Kd**3 + B*D*F*I/Kd**3 + B*D*G*I/Kd**3 + B*D*H*I/Kd**3 + B*D*I*J/Kd**3 + B*D*I/Kd**2 + B*E*F*I/Kd**3 + B*E*G*I/Kd**3 + B*E*H*I/Kd**3 + B*E*I*J/Kd**3 + B*E*I/Kd**2 + B*F*G*I/Kd**3 + B*F*H*I/Kd**3 + B*F*I*J/Kd**3 + B*F*I/Kd**2 + B*G*H*I/Kd**3 + B*G*I*J/Kd**3 + B*G*I/Kd**2 + B*H*I*J/Kd**3 + B*H*I/Kd**2 + B*I*J/Kd**2 + B*I/Kd + C*D*E*I/Kd**3 + C*D*F*I/Kd**3 + C*D*G*I/Kd**3 + C*D*H*I/Kd**3 + C*D*I*J/Kd**3 + C*D*I/Kd**2 + C*E*F*I/Kd**3 + C*E*G*I/Kd**3 + C*E*H*I/Kd**3 + C*E*I*J/Kd**3 + C*E*I/Kd**2 + C*F*G*I/Kd**3 + C*F*H*I/Kd**3 + C*F*I*J/Kd**3 + C*F*I/Kd**2 + C*G*H*I/Kd**3 + C*G*I*J/Kd**3 + C*G*I/Kd**2 + C*H*I*J/Kd**3 + C*H*I/Kd**2 + C*I*J/Kd**2 + C*I/Kd + D*E*F*I/Kd**3 + D*E*G*I/Kd**3 + D*E*H*I/Kd**3 + D*E*I*J/Kd**3 + D*E*I/Kd**2 + D*F*G*I/Kd**3 + D*F*H*I/Kd**3 + D*F*I*J/Kd**3 + D*F*I/Kd**2 + D*G*H*I/Kd**3 + D*G*I*J/Kd**3 + D*G*I/Kd**2 + D*H*I*J/Kd**3 + D*H*I/Kd**2 + D*I*J/Kd**2 + D*I/Kd + E*F*G*I/Kd**3 + E*F*H*I/Kd**3 + E*F*I*J/Kd**3 + E*F*I/Kd**2 + E*G*H*I/Kd**3 + E*G*I*J/Kd**3 + E*G*I/Kd**2 + E*H*I*J/Kd**3 + E*H*I/Kd**2 + E*I*J/Kd**2 + E*I/Kd + F*G*H*I/Kd**3 + F*G*I*J/Kd**3 + F*G*I/Kd**2 + F*H*I*J/Kd**3 + F*H*I/Kd**2 + F*I*J/Kd**2 + F*I/Kd + G*H*I*J/Kd**3 + G*H*I/Kd**2 + G*I*J/Kd**2 + G*I/Kd + H*I*J/Kd**2 + H*I/Kd + I*J/Kd + I - I_tot) / I_tot
    result[7] = (A*B*C*D/Kd**3 + A*B*D*E/Kd**3 + A*B*D*F/Kd**3 + A*B*D*G/Kd**3 + A*B*D*H/Kd**3 + A*B*D*I/Kd**3 + A*B*D*J/Kd**3 + A*B*D/Kd**2 + A*C*D*E/Kd**3 + A*C*D*F/Kd**3 + A*C*D*G/Kd**3 + A*C*D*H/Kd**3 + A*C*D*I/Kd**3 + A*C*D*J/Kd**3 + A*C*D/Kd**2 + A*D*E*F/Kd**3 + A*D*E*G/Kd**3 + A*D*E*H/Kd**3 + A*D*E*I/Kd**3 + A*D*E*J/Kd**3 + A*D*E/Kd**2 + A*D*F*G/Kd**3 + A*D*F*H/Kd**3 + A*D*F*I/Kd**3 + A*D*F*J/Kd**3 + A*D*F/Kd**2 + A*D*G*H/Kd**3 + A*D*G*I/Kd**3 + A*D*G*J/Kd**3 + A*D*G/Kd**2 + A*D*H*I/Kd**3 + A*D*H*J/Kd**3 + A*D*H/Kd**2 + A*D*I*J/Kd**3 + A*D*I/Kd**2 + A*D*J/Kd**2 + A*D/Kd + B*C*D*E/Kd**3 + B*C*D*F/Kd**3 + B*C*D*G/Kd**3 + B*C*D*H/Kd**3 + B*C*D*I/Kd**3 + B*C*D*J/Kd**3 + B*C*D/Kd**2 + B*D*E*F/Kd**3 + B*D*E*G/Kd**3 + B*D*E*H/Kd**3 + B*D*E*I/Kd**3 + B*D*E*J/Kd**3 + B*D*E/Kd**2 + B*D*F*G/Kd**3 + B*D*F*H/Kd**3 + B*D*F*I/Kd**3 + B*D*F*J/Kd**3 + B*D*F/Kd**2 + B*D*G*H/Kd**3 + B*D*G*I/Kd**3 + B*D*G*J/Kd**3 + B*D*G/Kd**2 + B*D*H*I/Kd**3 + B*D*H*J/Kd**3 + B*D*H/Kd**2 + B*D*I*J/Kd**3 + B*D*I/Kd**2 + B*D*J/Kd**2 + B*D/Kd + C*D*E*F/Kd**3 + C*D*E*G/Kd**3 + C*D*E*H/Kd**3 + C*D*E*I/Kd**3 + C*D*E*J/Kd**3 + C*D*E/Kd**2 + C*D*F*G/Kd**3 + C*D*F*H/Kd**3 + C*D*F*I/Kd**3 + C*D*F*J/Kd**3 + C*D*F/Kd**2 + C*D*G*H/Kd**3 + C*D*G*I/Kd**3 + C*D*G*J/Kd**3 + C*D*G/Kd**2 + C*D*H*I/Kd**3 + C*D*H*J/Kd**3 + C*D*H/Kd**2 + C*D*I*J/Kd**3 + C*D*I/Kd**2 + C*D*J/Kd**2 + C*D/Kd + D*E*F*G/Kd**3 + D*E*F*H/Kd**3 + D*E*F*I/Kd**3 + D*E*F*J/Kd**3 + D*E*F/Kd**2 + D*E*G*H/Kd**3 + D*E*G*I/Kd**3 + D*E*G*J/Kd**3 + D*E*G/Kd**2 + D*E*H*I/Kd**3 + D*E*H*J/Kd**3 + D*E*H/Kd**2 + D*E*I*J/Kd**3 + D*E*I/Kd**2 + D*E*J/Kd**2 + D*E/Kd + D*F*G*H/Kd**3 + D*F*G*I/Kd**3 + D*F*G*J/Kd**3 + D*F*G/Kd**2 + D*F*H*I/Kd**3 + D*F*H*J/Kd**3 + D*F*H/Kd**2 + D*F*I*J/Kd**3 + D*F*I/Kd**2 + D*F*J/Kd**2 + D*F/Kd + D*G*H*I/Kd**3 + D*G*H*J/Kd**3 + D*G*H/Kd**2 + D*G*I*J/Kd**3 + D*G*I/Kd**2 + D*G*J/Kd**2 + D*G/Kd + D*H*I*J/Kd**3 + D*H*I/Kd**2 + D*H*J/Kd**2 + D*H/Kd + D*I*J/Kd**2 + D*I/Kd + D*J/Kd + D - D_tot) / D_tot
    result[8] = (A*B*C*H/Kd**3 + A*B*D*H/Kd**3 + A*B*E*H/Kd**3 + A*B*F*H/Kd**3 + A*B*G*H/Kd**3 + A*B*H*I/Kd**3 + A*B*H*J/Kd**3 + A*B*H/Kd**2 + A*C*D*H/Kd**3 + A*C*E*H/Kd**3 + A*C*F*H/Kd**3 + A*C*G*H/Kd**3 + A*C*H*I/Kd**3 + A*C*H*J/Kd**3 + A*C*H/Kd**2 + A*D*E*H/Kd**3 + A*D*F*H/Kd**3 + A*D*G*H/Kd**3 + A*D*H*I/Kd**3 + A*D*H*J/Kd**3 + A*D*H/Kd**2 + A*E*F*H/Kd**3 + A*E*G*H/Kd**3 + A*E*H*I/Kd**3 + A*E*H*J/Kd**3 + A*E*H/Kd**2 + A*F*G*H/Kd**3 + A*F*H*I/Kd**3 + A*F*H*J/Kd**3 + A*F*H/Kd**2 + A*G*H*I/Kd**3 + A*G*H*J/Kd**3 + A*G*H/Kd**2 + A*H*I*J/Kd**3 + A*H*I/Kd**2 + A*H*J/Kd**2 + A*H/Kd + B*C*D*H/Kd**3 + B*C*E*H/Kd**3 + B*C*F*H/Kd**3 + B*C*G*H/Kd**3 + B*C*H*I/Kd**3 + B*C*H*J/Kd**3 + B*C*H/Kd**2 + B*D*E*H/Kd**3 + B*D*F*H/Kd**3 + B*D*G*H/Kd**3 + B*D*H*I/Kd**3 + B*D*H*J/Kd**3 + B*D*H/Kd**2 + B*E*F*H/Kd**3 + B*E*G*H/Kd**3 + B*E*H*I/Kd**3 + B*E*H*J/Kd**3 + B*E*H/Kd**2 + B*F*G*H/Kd**3 + B*F*H*I/Kd**3 + B*F*H*J/Kd**3 + B*F*H/Kd**2 + B*G*H*I/Kd**3 + B*G*H*J/Kd**3 + B*G*H/Kd**2 + B*H*I*J/Kd**3 + B*H*I/Kd**2 + B*H*J/Kd**2 + B*H/Kd + C*D*E*H/Kd**3 + C*D*F*H/Kd**3 + C*D*G*H/Kd**3 + C*D*H*I/Kd**3 + C*D*H*J/Kd**3 + C*D*H/Kd**2 + C*E*F*H/Kd**3 + C*E*G*H/Kd**3 + C*E*H*I/Kd**3 + C*E*H*J/Kd**3 + C*E*H/Kd**2 + C*F*G*H/Kd**3 + C*F*H*I/Kd**3 + C*F*H*J/Kd**3 + C*F*H/Kd**2 + C*G*H*I/Kd**3 + C*G*H*J/Kd**3 + C*G*H/Kd**2 + C*H*I*J/Kd**3 + C*H*I/Kd**2 + C*H*J/Kd**2 + C*H/Kd + D*E*F*H/Kd**3 + D*E*G*H/Kd**3 + D*E*H*I/Kd**3 + D*E*H*J/Kd**3 + D*E*H/Kd**2 + D*F*G*H/Kd**3 + D*F*H*I/Kd**3 + D*F*H*J/Kd**3 + D*F*H/Kd**2 + D*G*H*I/Kd**3 + D*G*H*J/Kd**3 + D*G*H/Kd**2 + D*H*I*J/Kd**3 + D*H*I/Kd**2 + D*H*J/Kd**2 + D*H/Kd + E*F*G*H/Kd**3 + E*F*H*I/Kd**3 + E*F*H*J/Kd**3 + E*F*H/Kd**2 + E*G*H*I/Kd**3 + E*G*H*J/Kd**3 + E*G*H/Kd**2 + E*H*I*J/Kd**3 + E*H*I/Kd**2 + E*H*J/Kd**2 + E*H/Kd + F*G*H*I/Kd**3 + F*G*H*J/Kd**3 + F*G*H/Kd**2 + F*H*I*J/Kd**3 + F*H*I/Kd**2 + F*H*J/Kd**2 + F*H/Kd + G*H*I*J/Kd**3 + G*H*I/Kd**2 + G*H*J/Kd**2 + G*H/Kd + H*I*J/Kd**2 + H*I/Kd + H*J/Kd + H - H_tot) / H_tot
    result[9] = (A*B*C*D/Kd**3 + A*B*C*E/Kd**3 + A*B*C*F/Kd**3 + A*B*C*G/Kd**3 + A*B*C*H/Kd**3 + A*B*C*I/Kd**3 + A*B*C*J/Kd**3 + A*B*C/Kd**2 + A*C*D*E/Kd**3 + A*C*D*F/Kd**3 + A*C*D*G/Kd**3 + A*C*D*H/Kd**3 + A*C*D*I/Kd**3 + A*C*D*J/Kd**3 + A*C*D/Kd**2 + A*C*E*F/Kd**3 + A*C*E*G/Kd**3 + A*C*E*H/Kd**3 + A*C*E*I/Kd**3 + A*C*E*J/Kd**3 + A*C*E/Kd**2 + A*C*F*G/Kd**3 + A*C*F*H/Kd**3 + A*C*F*I/Kd**3 + A*C*F*J/Kd**3 + A*C*F/Kd**2 + A*C*G*H/Kd**3 + A*C*G*I/Kd**3 + A*C*G*J/Kd**3 + A*C*G/Kd**2 + A*C*H*I/Kd**3 + A*C*H*J/Kd**3 + A*C*H/Kd**2 + A*C*I*J/Kd**3 + A*C*I/Kd**2 + A*C*J/Kd**2 + A*C/Kd + B*C*D*E/Kd**3 + B*C*D*F/Kd**3 + B*C*D*G/Kd**3 + B*C*D*H/Kd**3 + B*C*D*I/Kd**3 + B*C*D*J/Kd**3 + B*C*D/Kd**2 + B*C*E*F/Kd**3 + B*C*E*G/Kd**3 + B*C*E*H/Kd**3 + B*C*E*I/Kd**3 + B*C*E*J/Kd**3 + B*C*E/Kd**2 + B*C*F*G/Kd**3 + B*C*F*H/Kd**3 + B*C*F*I/Kd**3 + B*C*F*J/Kd**3 + B*C*F/Kd**2 + B*C*G*H/Kd**3 + B*C*G*I/Kd**3 + B*C*G*J/Kd**3 + B*C*G/Kd**2 + B*C*H*I/Kd**3 + B*C*H*J/Kd**3 + B*C*H/Kd**2 + B*C*I*J/Kd**3 + B*C*I/Kd**2 + B*C*J/Kd**2 + B*C/Kd + C*D*E*F/Kd**3 + C*D*E*G/Kd**3 + C*D*E*H/Kd**3 + C*D*E*I/Kd**3 + C*D*E*J/Kd**3 + C*D*E/Kd**2 + C*D*F*G/Kd**3 + C*D*F*H/Kd**3 + C*D*F*I/Kd**3 + C*D*F*J/Kd**3 + C*D*F/Kd**2 + C*D*G*H/Kd**3 + C*D*G*I/Kd**3 + C*D*G*J/Kd**3 + C*D*G/Kd**2 + C*D*H*I/Kd**3 + C*D*H*J/Kd**3 + C*D*H/Kd**2 + C*D*I*J/Kd**3 + C*D*I/Kd**2 + C*D*J/Kd**2 + C*D/Kd + C*E*F*G/Kd**3 + C*E*F*H/Kd**3 + C*E*F*I/Kd**3 + C*E*F*J/Kd**3 + C*E*F/Kd**2 + C*E*G*H/Kd**3 + C*E*G*I/Kd**3 + C*E*G*J/Kd**3 + C*E*G/Kd**2 + C*E*H*I/Kd**3 + C*E*H*J/Kd**3 + C*E*H/Kd**2 + C*E*I*J/Kd**3 + C*E*I/Kd**2 + C*E*J/Kd**2 + C*E/Kd + C*F*G*H/Kd**3 + C*F*G*I/Kd**3 + C*F*G*J/Kd**3 + C*F*G/Kd**2 + C*F*H*I/Kd**3 + C*F*H*J/Kd**3 + C*F*H/Kd**2 + C*F*I*J/Kd**3 + C*F*I/Kd**2 + C*F*J/Kd**2 + C*F/Kd + C*G*H*I/Kd**3 + C*G*H*J/Kd**3 + C*G*H/Kd**2 + C*G*I*J/Kd**3 + C*G*I/Kd**2 + C*G*J/Kd**2 + C*G/Kd + C*H*I*J/Kd**3 + C*H*I/Kd**2 + C*H*J/Kd**2 + C*H/Kd + C*I*J/Kd**2 + C*I/Kd + C*J/Kd + C - C_tot) / C_tot
    return result 


def update_state(solution, state):
    """
    Given a solution to the system_equations, update the state object to 
    reflect this solution.
    """
    # Independent variables
    state.B = solution[0]
    state.F = solution[1]
    state.J = solution[2]
    state.G = solution[3]
    state.A = solution[4]
    state.E = solution[5]
    state.I = solution[6]
    state.D = solution[7]
    state.H = solution[8]
    state.C = solution[9]

    # Readability 
    A = state.A
    B = state.B
    C = state.C
    D = state.D
    E = state.E
    F = state.F
    G = state.G
    H = state.H
    I = state.I
    J = state.J
    Kd = state.Kd

    # Dependent variables
    state.AB = A*B/Kd
    state.AC = A*C/Kd
    state.AD = A*D/Kd
    state.AE = A*E/Kd
    state.AF = A*F/Kd
    state.AG = A*G/Kd
    state.AH = A*H/Kd
    state.AI = A*I/Kd
    state.AJ = A*J/Kd
    state.BC = B*C/Kd
    state.BD = B*D/Kd
    state.BE = B*E/Kd
    state.BF = B*F/Kd
    state.BG = B*G/Kd
    state.BH = B*H/Kd
    state.BI = B*I/Kd
    state.BJ = B*J/Kd
    state.CD = C*D/Kd
    state.CE = C*E/Kd
    state.CF = C*F/Kd
    state.CG = C*G/Kd
    state.CH = C*H/Kd
    state.CI = C*I/Kd
    state.CJ = C*J/Kd
    state.DE = D*E/Kd
    state.DF = D*F/Kd
    state.DG = D*G/Kd
    state.DH = D*H/Kd
    state.DI = D*I/Kd
    state.DJ = D*J/Kd
    state.EF = E*F/Kd
    state.EG = E*G/Kd
    state.EH = E*H/Kd
    state.EI = E*I/Kd
    state.EJ = E*J/Kd
    state.FG = F*G/Kd
    state.FH = F*H/Kd
    state.FI = F*I/Kd
    state.FJ = F*J/Kd
    state.GH = G*H/Kd
    state.GI = G*I/Kd
    state.GJ = G*J/Kd
    state.HI = H*I/Kd
    state.HJ = H*J/Kd
    state.IJ = I*J/Kd
    state.ABC = A*B*C/Kd**2
    state.ABD = A*B*D/Kd**2
    state.ABE = A*B*E/Kd**2
    state.ABF = A*B*F/Kd**2
    state.ABG = A*B*G/Kd**2
    state.ABH = A*B*H/Kd**2
    state.ABI = A*B*I/Kd**2
    state.ABJ = A*B*J/Kd**2
    state.ACD = A*C*D/Kd**2
    state.ACE = A*C*E/Kd**2
    state.ACF = A*C*F/Kd**2
    state.ACG = A*C*G/Kd**2
    state.ACH = A*C*H/Kd**2
    state.ACI = A*C*I/Kd**2
    state.ACJ = A*C*J/Kd**2
    state.ADE = A*D*E/Kd**2
    state.ADF = A*D*F/Kd**2
    state.ADG = A*D*G/Kd**2
    state.ADH = A*D*H/Kd**2
    state.ADI = A*D*I/Kd**2
    state.ADJ = A*D*J/Kd**2
    state.AEF = A*E*F/Kd**2
    state.AEG = A*E*G/Kd**2
    state.AEH = A*E*H/Kd**2
    state.AEI = A*E*I/Kd**2
    state.AEJ = A*E*J/Kd**2
    state.AFG = A*F*G/Kd**2
    state.AFH = A*F*H/Kd**2
    state.AFI = A*F*I/Kd**2
    state.AFJ = A*F*J/Kd**2
    state.AGH = A*G*H/Kd**2
    state.AGI = A*G*I/Kd**2
    state.AGJ = A*G*J/Kd**2
    state.AHI = A*H*I/Kd**2
    state.AHJ = A*H*J/Kd**2
    state.AIJ = A*I*J/Kd**2
    state.BCD = B*C*D/Kd**2
    state.BCE = B*C*E/Kd**2
    state.BCF = B*C*F/Kd**2
    state.BCG = B*C*G/Kd**2
    state.BCH = B*C*H/Kd**2
    state.BCI = B*C*I/Kd**2
    state.BCJ = B*C*J/Kd**2
    state.BDE = B*D*E/Kd**2
    state.BDF = B*D*F/Kd**2
    state.BDG = B*D*G/Kd**2
    state.BDH = B*D*H/Kd**2
    state.BDI = B*D*I/Kd**2
    state.BDJ = B*D*J/Kd**2
    state.BEF = B*E*F/Kd**2
    state.BEG = B*E*G/Kd**2
    state.BEH = B*E*H/Kd**2
    state.BEI = B*E*I/Kd**2
    state.BEJ = B*E*J/Kd**2
    state.BFG = B*F*G/Kd**2
    state.BFH = B*F*H/Kd**2
    state.BFI = B*F*I/Kd**2
    state.BFJ = B*F*J/Kd**2
    state.BGH = B*G*H/Kd**2
    state.BGI = B*G*I/Kd**2
    state.BGJ = B*G*J/Kd**2
    state.BHI = B*H*I/Kd**2
    state.BHJ = B*H*J/Kd**2
    state.BIJ = B*I*J/Kd**2
    state.CDE = C*D*E/Kd**2
    state.CDF = C*D*F/Kd**2
    state.CDG = C*D*G/Kd**2
    state.CDH = C*D*H/Kd**2
    state.CDI = C*D*I/Kd**2
    state.CDJ = C*D*J/Kd**2
    state.CEF = C*E*F/Kd**2
    state.CEG = C*E*G/Kd**2
    state.CEH = C*E*H/Kd**2
    state.CEI = C*E*I/Kd**2
    state.CEJ = C*E*J/Kd**2
    state.CFG = C*F*G/Kd**2
    state.CFH = C*F*H/Kd**2
    state.CFI = C*F*I/Kd**2
    state.CFJ = C*F*J/Kd**2
    state.CGH = C*G*H/Kd**2
    state.CGI = C*G*I/Kd**2
    state.CGJ = C*G*J/Kd**2
    state.CHI = C*H*I/Kd**2
    state.CHJ = C*H*J/Kd**2
    state.CIJ = C*I*J/Kd**2
    state.DEF = D*E*F/Kd**2
    state.DEG = D*E*G/Kd**2
    state.DEH = D*E*H/Kd**2
    state.DEI = D*E*I/Kd**2
    state.DEJ = D*E*J/Kd**2
    state.DFG = D*F*G/Kd**2
    state.DFH = D*F*H/Kd**2
    state.DFI = D*F*I/Kd**2
    state.DFJ = D*F*J/Kd**2
    state.DGH = D*G*H/Kd**2
    state.DGI = D*G*I/Kd**2
    state.DGJ = D*G*J/Kd**2
    state.DHI = D*H*I/Kd**2
    state.DHJ = D*H*J/Kd**2
    state.DIJ = D*I*J/Kd**2
    state.EFG = E*F*G/Kd**2
    state.EFH = E*F*H/Kd**2
    state.EFI = E*F*I/Kd**2
    state.EFJ = E*F*J/Kd**2
    state.EGH = E*G*H/Kd**2
    state.EGI = E*G*I/Kd**2
    state.EGJ = E*G*J/Kd**2
    state.EHI = E*H*I/Kd**2
    state.EHJ = E*H*J/Kd**2
    state.EIJ = E*I*J/Kd**2
    state.FGH = F*G*H/Kd**2
    state.FGI = F*G*I/Kd**2
    state.FGJ = F*G*J/Kd**2
    state.FHI = F*H*I/Kd**2
    state.FHJ = F*H*J/Kd**2
    state.FIJ = F*I*J/Kd**2
    state.GHI = G*H*I/Kd**2
    state.GHJ = G*H*J/Kd**2
    state.GIJ = G*I*J/Kd**2
    state.HIJ = H*I*J/Kd**2
    state.ABCD = A*B*C*D/Kd**3
    state.ABCE = A*B*C*E/Kd**3
    state.ABCF = A*B*C*F/Kd**3
    state.ABCG = A*B*C*G/Kd**3
    state.ABCH = A*B*C*H/Kd**3
    state.ABCI = A*B*C*I/Kd**3
    state.ABCJ = A*B*C*J/Kd**3
    state.ABDE = A*B*D*E/Kd**3
    state.ABDF = A*B*D*F/Kd**3
    state.ABDG = A*B*D*G/Kd**3
    state.ABDH = A*B*D*H/Kd**3
    state.ABDI = A*B*D*I/Kd**3
    state.ABDJ = A*B*D*J/Kd**3
    state.ABEF = A*B*E*F/Kd**3
    state.ABEG = A*B*E*G/Kd**3
    state.ABEH = A*B*E*H/Kd**3
    state.ABEI = A*B*E*I/Kd**3
    state.ABEJ = A*B*E*J/Kd**3
    state.ABFG = A*B*F*G/Kd**3
    state.ABFH = A*B*F*H/Kd**3
    state.ABFI = A*B*F*I/Kd**3
    state.ABFJ = A*B*F*J/Kd**3
    state.ABGH = A*B*G*H/Kd**3
    state.ABGI = A*B*G*I/Kd**3
    state.ABGJ = A*B*G*J/Kd**3
    state.ABHI = A*B*H*I/Kd**3
    state.ABHJ = A*B*H*J/Kd**3
    state.ABIJ = A*B*I*J/Kd**3
    state.ACDE = A*C*D*E/Kd**3
    state.ACDF = A*C*D*F/Kd**3
    state.ACDG = A*C*D*G/Kd**3
    state.ACDH = A*C*D*H/Kd**3
    state.ACDI = A*C*D*I/Kd**3
    state.ACDJ = A*C*D*J/Kd**3
    state.ACEF = A*C*E*F/Kd**3
    state.ACEG = A*C*E*G/Kd**3
    state.ACEH = A*C*E*H/Kd**3
    state.ACEI = A*C*E*I/Kd**3
    state.ACEJ = A*C*E*J/Kd**3
    state.ACFG = A*C*F*G/Kd**3
    state.ACFH = A*C*F*H/Kd**3
    state.ACFI = A*C*F*I/Kd**3
    state.ACFJ = A*C*F*J/Kd**3
    state.ACGH = A*C*G*H/Kd**3
    state.ACGI = A*C*G*I/Kd**3
    state.ACGJ = A*C*G*J/Kd**3
    state.ACHI = A*C*H*I/Kd**3
    state.ACHJ = A*C*H*J/Kd**3
    state.ACIJ = A*C*I*J/Kd**3
    state.ADEF = A*D*E*F/Kd**3
    state.ADEG = A*D*E*G/Kd**3
    state.ADEH = A*D*E*H/Kd**3
    state.ADEI = A*D*E*I/Kd**3
    state.ADEJ = A*D*E*J/Kd**3
    state.ADFG = A*D*F*G/Kd**3
    state.ADFH = A*D*F*H/Kd**3
    state.ADFI = A*D*F*I/Kd**3
    state.ADFJ = A*D*F*J/Kd**3
    state.ADGH = A*D*G*H/Kd**3
    state.ADGI = A*D*G*I/Kd**3
    state.ADGJ = A*D*G*J/Kd**3
    state.ADHI = A*D*H*I/Kd**3
    state.ADHJ = A*D*H*J/Kd**3
    state.ADIJ = A*D*I*J/Kd**3
    state.AEFG = A*E*F*G/Kd**3
    state.AEFH = A*E*F*H/Kd**3
    state.AEFI = A*E*F*I/Kd**3
    state.AEFJ = A*E*F*J/Kd**3
    state.AEGH = A*E*G*H/Kd**3
    state.AEGI = A*E*G*I/Kd**3
    state.AEGJ = A*E*G*J/Kd**3
    state.AEHI = A*E*H*I/Kd**3
    state.AEHJ = A*E*H*J/Kd**3
    state.AEIJ = A*E*I*J/Kd**3
    state.AFGH = A*F*G*H/Kd**3
    state.AFGI = A*F*G*I/Kd**3
    state.AFGJ = A*F*G*J/Kd**3
    state.AFHI = A*F*H*I/Kd**3
    state.AFHJ = A*F*H*J/Kd**3
    state.AFIJ = A*F*I*J/Kd**3
    state.AGHI = A*G*H*I/Kd**3
    state.AGHJ = A*G*H*J/Kd**3
    state.AGIJ = A*G*I*J/Kd**3
    state.AHIJ = A*H*I*J/Kd**3
    state.BCDE = B*C*D*E/Kd**3
    state.BCDF = B*C*D*F/Kd**3
    state.BCDG = B*C*D*G/Kd**3
    state.BCDH = B*C*D*H/Kd**3
    state.BCDI = B*C*D*I/Kd**3
    state.BCDJ = B*C*D*J/Kd**3
    state.BCEF = B*C*E*F/Kd**3
    state.BCEG = B*C*E*G/Kd**3
    state.BCEH = B*C*E*H/Kd**3
    state.BCEI = B*C*E*I/Kd**3
    state.BCEJ = B*C*E*J/Kd**3
    state.BCFG = B*C*F*G/Kd**3
    state.BCFH = B*C*F*H/Kd**3
    state.BCFI = B*C*F*I/Kd**3
    state.BCFJ = B*C*F*J/Kd**3
    state.BCGH = B*C*G*H/Kd**3
    state.BCGI = B*C*G*I/Kd**3
    state.BCGJ = B*C*G*J/Kd**3
    state.BCHI = B*C*H*I/Kd**3
    state.BCHJ = B*C*H*J/Kd**3
    state.BCIJ = B*C*I*J/Kd**3
    state.BDEF = B*D*E*F/Kd**3
    state.BDEG = B*D*E*G/Kd**3
    state.BDEH = B*D*E*H/Kd**3
    state.BDEI = B*D*E*I/Kd**3
    state.BDEJ = B*D*E*J/Kd**3
    state.BDFG = B*D*F*G/Kd**3
    state.BDFH = B*D*F*H/Kd**3
    state.BDFI = B*D*F*I/Kd**3
    state.BDFJ = B*D*F*J/Kd**3
    state.BDGH = B*D*G*H/Kd**3
    state.BDGI = B*D*G*I/Kd**3
    state.BDGJ = B*D*G*J/Kd**3
    state.BDHI = B*D*H*I/Kd**3
    state.BDHJ = B*D*H*J/Kd**3
    state.BDIJ = B*D*I*J/Kd**3
    state.BEFG = B*E*F*G/Kd**3
    state.BEFH = B*E*F*H/Kd**3
    state.BEFI = B*E*F*I/Kd**3
    state.BEFJ = B*E*F*J/Kd**3
    state.BEGH = B*E*G*H/Kd**3
    state.BEGI = B*E*G*I/Kd**3
    state.BEGJ = B*E*G*J/Kd**3
    state.BEHI = B*E*H*I/Kd**3
    state.BEHJ = B*E*H*J/Kd**3
    state.BEIJ = B*E*I*J/Kd**3
    state.BFGH = B*F*G*H/Kd**3
    state.BFGI = B*F*G*I/Kd**3
    state.BFGJ = B*F*G*J/Kd**3
    state.BFHI = B*F*H*I/Kd**3
    state.BFHJ = B*F*H*J/Kd**3
    state.BFIJ = B*F*I*J/Kd**3
    state.BGHI = B*G*H*I/Kd**3
    state.BGHJ = B*G*H*J/Kd**3
    state.BGIJ = B*G*I*J/Kd**3
    state.BHIJ = B*H*I*J/Kd**3
    state.CDEF = C*D*E*F/Kd**3
    state.CDEG = C*D*E*G/Kd**3
    state.CDEH = C*D*E*H/Kd**3
    state.CDEI = C*D*E*I/Kd**3
    state.CDEJ = C*D*E*J/Kd**3
    state.CDFG = C*D*F*G/Kd**3
    state.CDFH = C*D*F*H/Kd**3
    state.CDFI = C*D*F*I/Kd**3
    state.CDFJ = C*D*F*J/Kd**3
    state.CDGH = C*D*G*H/Kd**3
    state.CDGI = C*D*G*I/Kd**3
    state.CDGJ = C*D*G*J/Kd**3
    state.CDHI = C*D*H*I/Kd**3
    state.CDHJ = C*D*H*J/Kd**3
    state.CDIJ = C*D*I*J/Kd**3
    state.CEFG = C*E*F*G/Kd**3
    state.CEFH = C*E*F*H/Kd**3
    state.CEFI = C*E*F*I/Kd**3
    state.CEFJ = C*E*F*J/Kd**3
    state.CEGH = C*E*G*H/Kd**3
    state.CEGI = C*E*G*I/Kd**3
    state.CEGJ = C*E*G*J/Kd**3
    state.CEHI = C*E*H*I/Kd**3
    state.CEHJ = C*E*H*J/Kd**3
    state.CEIJ = C*E*I*J/Kd**3
    state.CFGH = C*F*G*H/Kd**3
    state.CFGI = C*F*G*I/Kd**3
    state.CFGJ = C*F*G*J/Kd**3
    state.CFHI = C*F*H*I/Kd**3
    state.CFHJ = C*F*H*J/Kd**3
    state.CFIJ = C*F*I*J/Kd**3
    state.CGHI = C*G*H*I/Kd**3
    state.CGHJ = C*G*H*J/Kd**3
    state.CGIJ = C*G*I*J/Kd**3
    state.CHIJ = C*H*I*J/Kd**3
    state.DEFG = D*E*F*G/Kd**3
    state.DEFH = D*E*F*H/Kd**3
    state.DEFI = D*E*F*I/Kd**3
    state.DEFJ = D*E*F*J/Kd**3
    state.DEGH = D*E*G*H/Kd**3
    state.DEGI = D*E*G*I/Kd**3
    state.DEGJ = D*E*G*J/Kd**3
    state.DEHI = D*E*H*I/Kd**3
    state.DEHJ = D*E*H*J/Kd**3
    state.DEIJ = D*E*I*J/Kd**3
    state.DFGH = D*F*G*H/Kd**3
    state.DFGI = D*F*G*I/Kd**3
    state.DFGJ = D*F*G*J/Kd**3
    state.DFHI = D*F*H*I/Kd**3
    state.DFHJ = D*F*H*J/Kd**3
    state.DFIJ = D*F*I*J/Kd**3
    state.DGHI = D*G*H*I/Kd**3
    state.DGHJ = D*G*H*J/Kd**3
    state.DGIJ = D*G*I*J/Kd**3
    state.DHIJ = D*H*I*J/Kd**3
    state.EFGH = E*F*G*H/Kd**3
    state.EFGI = E*F*G*I/Kd**3
    state.EFGJ = E*F*G*J/Kd**3
    state.EFHI = E*F*H*I/Kd**3
    state.EFHJ = E*F*H*J/Kd**3
    state.EFIJ = E*F*I*J/Kd**3
    state.EGHI = E*G*H*I/Kd**3
    state.EGHJ = E*G*H*J/Kd**3
    state.EGIJ = E*G*I*J/Kd**3
    state.EHIJ = E*H*I*J/Kd**3
    state.FGHI = F*G*H*I/Kd**3
    state.FGHJ = F*G*H*J/Kd**3
    state.FGIJ = F*G*I*J/Kd**3
    state.FHIJ = F*H*I*J/Kd**3
    state.GHIJ = G*H*I*J/Kd**3


def data_function(state):
    """
    Function to map state object to experimental data values.
    """
    # Readability
    A = state.A
    AB = state.AB
    ABC = state.ABC
    ABCD = state.ABCD
    ABCE = state.ABCE
    ABCF = state.ABCF
    ABCG = state.ABCG
    ABCH = state.ABCH
    ABCI = state.ABCI
    ABCJ = state.ABCJ
    ABD = state.ABD
    ABDE = state.ABDE
    ABDF = state.ABDF
    ABDG = state.ABDG
    ABDH = state.ABDH
    ABDI = state.ABDI
    ABDJ = state.ABDJ
    ABE = state.ABE
    ABEF = state.ABEF
    ABEG = state.ABEG
    ABEH = state.ABEH
    ABEI = state.ABEI
    ABEJ = state.ABEJ
    ABF = state.ABF
    ABFG = state.ABFG
    ABFH = state.ABFH
    ABFI = state.ABFI
    ABFJ = state.ABFJ
    ABG = state.ABG
    ABGH = state.ABGH
    ABGI = state.ABGI
    ABGJ = state.ABGJ
    ABH = state.ABH
    ABHI = state.ABHI
    ABHJ = state.ABHJ
    ABI = state.ABI
    ABIJ = state.ABIJ
    ABJ = state.ABJ
    AC = state.AC
    ACD = state.ACD
    ACDE = state.ACDE
    ACDF = state.ACDF
    ACDG = state.ACDG
    ACDH = state.ACDH
    ACDI = state.ACDI
    ACDJ = state.ACDJ
    ACE = state.ACE
    ACEF = state.ACEF
    ACEG = state.ACEG
    ACEH = state.ACEH
    ACEI = state.ACEI
    ACEJ = state.ACEJ
    ACF = state.ACF
    ACFG = state.ACFG
    ACFH = state.ACFH
    ACFI = state.ACFI
    ACFJ = state.ACFJ
    ACG = state.ACG
    ACGH = state.ACGH
    ACGI = state.ACGI
    ACGJ = state.ACGJ
    ACH = state.ACH
    ACHI = state.ACHI
    ACHJ = state.ACHJ
    ACI = state.ACI
    ACIJ = state.ACIJ
    ACJ = state.ACJ
    AD = state.AD
    ADE = state.ADE
    ADEF = state.ADEF
    ADEG = state.ADEG
    ADEH = state.ADEH
    ADEI = state.ADEI
    ADEJ = state.ADEJ
    ADF = state.ADF
    ADFG = state.ADFG
    ADFH = state.ADFH
    ADFI = state.ADFI
    ADFJ = state.ADFJ
    ADG = state.ADG
    ADGH = state.ADGH
    ADGI = state.ADGI
    ADGJ = state.ADGJ
    ADH = state.ADH
    ADHI = state.ADHI
    ADHJ = state.ADHJ
    ADI = state.ADI
    ADIJ = state.ADIJ
    ADJ = state.ADJ
    AE = state.AE
    AEF = state.AEF
    AEFG = state.AEFG
    AEFH = state.AEFH
    AEFI = state.AEFI
    AEFJ = state.AEFJ
    AEG = state.AEG
    AEGH = state.AEGH
    AEGI = state.AEGI
    AEGJ = state.AEGJ
    AEH = state.AEH
    AEHI = state.AEHI
    AEHJ = state.AEHJ
    AEI = state.AEI
    AEIJ = state.AEIJ
    AEJ = state.AEJ
    AF = state.AF
    AFG = state.AFG
    AFGH = state.AFGH
    AFGI = state.AFGI
    AFGJ = state.AFGJ
    AFH = state.AFH
    AFHI = state.AFHI
    AFHJ = state.AFHJ
    AFI = state.AFI
    AFIJ = state.AFIJ
    AFJ = state.AFJ
    AG = state.AG
    AGH = state.AGH
    AGHI = state.AGHI
    AGHJ = state.AGHJ
    AGI = state.AGI
    AGIJ = state.AGIJ
    AGJ = state.AGJ
    AH = state.AH
    AHI = state.AHI
    AHIJ = state.AHIJ
    AHJ = state.AHJ
    AI = state.AI
    AIJ = state.AIJ
    AJ = state.AJ
    A_tot = state.A_tot
    data_max = state.data_max
    data_min = state.data_min

    return A*data_min/A_tot + data_max*(AB + ABC + ABCD + ABCE + ABCF + ABCG + ABCH + ABCI + ABCJ + ABD + ABDE + ABDF + ABDG + ABDH + ABDI + ABDJ + ABE + ABEF + ABEG + ABEH + ABEI + ABEJ + ABF + ABFG + ABFH + ABFI + ABFJ + ABG + ABGH + ABGI + ABGJ + ABH + ABHI + ABHJ + ABI + ABIJ + ABJ + AC + ACD + ACDE + ACDF + ACDG + ACDH + ACDI + ACDJ + ACE + ACEF + ACEG + ACEH + ACEI + ACEJ + ACF + ACFG + ACFH + ACFI + ACFJ + ACG + ACGH + ACGI + ACGJ + ACH + ACHI + ACHJ + ACI + ACIJ + ACJ + AD + ADE + ADEF + ADEG + ADEH + ADEI + ADEJ + ADF + ADFG + ADFH + ADFI + ADFJ + ADG + ADGH + ADGI + ADGJ + ADH + ADHI + ADHJ + ADI + ADIJ + ADJ + AE + AEF + AEFG + AEFH + AEFI + AEFJ + AEG + AEGH + AEGI + AEGJ + AEH + AEHI + AEHJ + AEI + AEIJ + AEJ + AF + AFG + AFGH + AFGI + AFGJ + AFH + AFHI + AFHJ + AFI + AFIJ + AFJ + AG + AGH + AGHI + AGHJ + AGI + AGIJ + AGJ + AH + AHI + AHIJ + AHJ + AI + AIJ + AJ)/A_tot


